[validator.heliax-gian]
consensus_public_key = "0095f76c5ceffda947ebf853665383b1cc2fe0b6547bc794f42bb6e9ce410aeeab"
account_public_key = "00d4d90608c939bace462545e9b334e6e698cfeb236c7a4c043c53949a659376bd"
staking_reward_public_key = "00cba9a116e29aaa4604a2acedcfe050bcefdabc6913fb27b5db9b45c1e99a8643"
protocol_public_key = "002d42f41c5078cdb7f92f8a5247cfa8ff91b4008661c5eae658a8c56bc4c14640"
dkg_public_key = "6000000061f050970a8065620a761bea05b60467c76a57145a77ade900006894276cf2d0232e3d3bf1d4cfa3f8a528b3a8639a0b3528703528719d14f61bc010f6fa1c7239b3e6d895ad6d93695704b84beb441c09b74a8e3402330155491375a157f910"
net_address = "63.32.210.222:26656"
tendermint_node_key = "001204080e8a56b007d330d5bdd10173ed54897dacf16fc4a15e2c69da33692e87"