[validator.heliax-marco]
consensus_public_key = "00a593bd5c5eece4e7c1d3533b943e0d370eab6666107b5bf3d0c05bef0bf6cb48"
account_public_key = "000368d756e0c5088d361069ea8b637e4664ac8dab6a7cb2de05f84a9a9ddea92f"
staking_reward_public_key = "00171281fb0f36c4d0f89537823e0aaed3b16ee38bdd3b2b321af5fa83c7cde377"
protocol_public_key = "00006e5bfce66c8ff2a88b0edc11a26a8d6c1d82fbb6c8d2dc73461d60ea0f65e9"
dkg_public_key = "60000000ddcfdf94a5294ffa408f13a37e5600bd069f6f261ebcbb88d1a813c6f12d227d971f9bf852974c7de536719b969b8804c1512cbea9ddc623dffd770f930a6888fd4eda596358cb5197bc5331f9e74d499ce765740442f5c3cf343afe20a1118e"
net_address = "46.101.131.231:26656"
tendermint_node_key = "00eff09c575d162484310b6fde835256e095a0a78c5a95d43c581710b776370d36"