[validator.heliax-memas]
account_public_key = "0002afebf93e2031fab596c34c9f57627696dbce54bb9ff263b4f80911449764f9"
consensus_public_key = "00899fc095aadecc5e32d15c0ae9568ea0ad208ebcc843c88235f867e68bc0493f"
dkg_public_key = "60000000f4ca935cd011e081acc10da3c95fbbd6f2afeef3a642caa533cc755f98f372f6c07d59baa26c303786e936456279aa12d8f445a165a6dbc0e4a0007b2cbad8006f5333467fbf0d040fdcdc84b40e44e16fd4f783d6de5851762ac2cf93b1ac8a"
net_address = "157.230.24.247:26656"
protocol_public_key = "0088bbd42f5e507b2f4f09f664e70649cb125f6990d4f028cc230137b442e803fd"
staking_reward_public_key = "00220543f3c0baeb439a7ef2fbabde5fb3100b4866e7fcada0cfd71a3489dc19cc"
tendermint_node_key = "00793e553ac29302a6febb2aa6b0bae801b7c4127bb2e6b8c3fb046a6f3f88b1a9"
