
[validator.amadison79]
consensus_public_key = "00f58a9e1262dbae8e2b9c1966e2745357c1a3d77c53e4b54406764342caa80a83"
account_public_key = "0004b4964e582b651e942ab981a29968c88b88f8dafde227e505c9880e23797ae1"
protocol_public_key = "004283e27733f5d80892e125d67b6548a845dc77df3074bf6971e34ef6a76a6654"
dkg_public_key = "60000000528003937cb099ceae03316e04c7774c65e8abbc01e3a67e0e153720c2cbf818a5481bbde2b5cc1704110bf675dcd702fc1c3dd35442d247feb577904db4af8eb0744511b677f76e03e611e3694d8bf3c2a034eea604813b67d5b579911e110b"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "109.205.182.127:26656"
tendermint_node_key = "004872a5cf3bd58f0fcbea1b1b61ce0abfaf37eed2f39a3abbdc6c0af337cbc983"
