[validator.gnosed]
consensus_public_key = "00083279d4a128ccec94c961ce30105e24ef5be95245a0667b8fc9374b9531a417"
account_public_key = "009f151bbf3f9656c328773ef8a1e0370cee571025cee9549da65f9d81d8bcf578"
staking_reward_public_key = "00df30507d637503bd93dcc63d84abbfc346ec9aaeb54efdb17462ccb0b8a3080a"
protocol_public_key = "0068337eba8f303c0c17384636f7ce1a79c04989b74d71d277d8b814e2440929e0"
dkg_public_key = "60000000e0985a103fb386e54c8e894a4f26720602937f1ff088b590b4f4b554ea44171d9912d472235ab7dcc3e349c9bce09618bbc151a338a1d1a236948ef1118ef77239eb7f7d94acfe256d0ba742c48b5f561b2afd49456bd5333c4488d79c892017"
net_address = "162.55.0.160:26656"
tendermint_node_key = "0036e7a66205a2b716731de08d6923f1f37beeadd1d4326f338651c613f943219f"
