[validator.jav1x]
consensus_public_key = "00aca4b2b3da760c5ab09d244640554da6831a9b71189cb64accb794589d07d455"
account_public_key = "0044b2c0e8b7c1deda962be241809e27a2f8df7c19247948549b4f59980b676671"
protocol_public_key = "006b640d603833896af12b8849b7c33ae9c1672193de5f6499f4ee0efd909ef51b"
dkg_public_key = "60000000cd1f5a08b6c988fd7e9a332714dc0332da50053411f0cb7824b803b77afa52f1fb5678b57a36f2048628223038cc2908c27611c25eca9484540474c8c48631b6a91dae9a3ebe4efc6af7ef30bfdee3d1a743db9f4224188e7fb6bc2f463b1b0b"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.199.62:26656"
tendermint_node_key = "00ed56bca1af9f27f4762c48199e5310ab4ace379a96ff14683828928a60599a19"
