[validator.marco]
consensus_public_key = "00c59584a2ba34741653608f0047e0a106c1393d863cc77ffb022491df9915011d"
account_public_key = "00d4f43d8ff4d6952315185b9236fda744be5a743cc59117741b622a248472f202"
staking_reward_public_key = "00f941e8134c8d11729df6b1134d53c18407f4e9361965a20d31e7d4690d2c1d24"
protocol_public_key = "008bbe726e4a1d9905f05f2b6a24489cdc263acd38dc84d0a630802ebab78001bc"
dkg_public_key = "6000000021bc854123e836bd5d3dee21a78a2002f7b0179c24304fa6bfbabcf6451786569d7b543ceee44eae02fe1191c5b5b70a3c190db9f8fa3016d78ca422a91cd61311753b92d2c6eafe9d74aa2a9b9b2d80722dcb561d9501c43fe49963df596391"
net_address = "2.229.203.200:26656"
tendermint_node_key = "007329cbc2abe8d420fdb3c4cef17aa364914124d2447fafbcd5f946ed253604ab"
