[validator.alkadeta]
consensus_public_key = "003f8e76bda18c3b44a07f2f446288bd8063b14a4b526a5403f415621b0016a079"
eth_cold_key = "01031f18ba7ae9427e7de8ab71d4d37f4770c93fed765a3bc6c52028738c0897a27e"
eth_hot_key = "0102267d7be87db8e8a2d8d85733a0eaa3fd284fc50d73e4e0d2881a03f4e86f3c6a"
account_public_key = "00ec0086f136a4fd7c6f866820f4ef7f1db15a12078a13b2717dc77f620582ccf9"
protocol_public_key = "00684fd2aa57409601989e3443b6147335e26b37de00791005d2d0356c3f01716c"
dkg_public_key = "6000000062ef7005402717e27d2032f8fbbd644fa0b440d13e62ec1a0c40e5014c9510f06c51c0fc3246085ff4580712a2b38d02f4eca6ad8c843109f7a4a8158c38813c92ed64459c2b7235f6cbccfd1e553907e42957abcd21dc14bca24839c4247b17"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:26656"
tendermint_node_key = "009ddacb61f81e8419827638cb9663db71e8275eae3128dc6fa4e8029937aace6a"
