[validator.Atomstaking]
consensus_public_key = "00c80309aa2a450a6fdf1c4428eb9d6a97ec2fe6d626dd589a07439da532357371"
eth_cold_key = "01037d4c7e4ac765011e713736a327ba33d3e037e89e5443f2bbf732c353667f83c8"
eth_hot_key = "010235d507070dff4d4f1bc80b21994fad7a2abeb8f8510e6d14d53ae95d5d90b3c3"
account_public_key = "007d2f803c768d551ddaf961db0a2dc9f84824b6308c0ce60cd545748b82ac2e72"
protocol_public_key = "00f51a660c7e9d465fcfd7f358efdb51a7a7194747705a62f14846a610dffadea3"
dkg_public_key = "600000000470e28de622847f9b5b9c5e8d79fc4c50de87b03f416a3fab57c3220406675118a83fdf182390a0bc4c4aad7b0009076f021c598f0c486a493a8e64b91b46b88810bb4f89bc250a87ed1befa514487c5f2db9c0ba9ddc15daa5b9d6cc648c86"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "13.250.9.214:26656"
tendermint_node_key = "0060502bae84411e5553b657de51d9cc37e025dc69d6551f2ac3846b7a4ab0a26b"