[validator.bigegg]
consensus_public_key = "00317afbc9520863029b8f319e03e65da1da46c68d6e0afb725c8baab4d8bcb9e7"
eth_cold_key = "0102ba6c2068f585e3829614cd12e8679dd9845a7a1c8e45edf7c2492b95d0b0109a"
eth_hot_key = "0103138568cd5b3d9589b01f9b11423079e7d33d7e041595822e50d74b90ea21844f"
account_public_key = "001c8a7d5cb0b64a4441ea9ac49c4fc6c5501b526e56830226f909f845e406a968"
protocol_public_key = "0080966ac59d9789c577c38c12e56f3c58beaebe4ff785380cf2443b999b2feb7e"
dkg_public_key = "6000000016f1c05f6f5840ef10e2150425d7848fca2926bcb7f849383064611a4b5c35d0cbc17cf5d817f7922d84369014af81051653186212179dcc0d4fdaf359965f5ae63dfc29c82564782400254a03e09321b315f5cc28faf7759bb5ab2e74588215"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "5.9.60.35:26656"
tendermint_node_key = "00811241823485d79ee1da191b35fb79fe2c5eb415e4112602812e3e5bb7594c51"
