[validator.deber]
consensus_public_key = "007c7f7ea5c092003aa0c052335b5502b7a1867c8f12fd75f1c2e5fd95735419a3"
eth_cold_key = "010208aea68f108ec6c452154c8e69b94675598147b1b8f0f508611bb5f95b59fc45"
eth_hot_key = "01038124706a4ec4012bec7281be954d322d9eb50768071d57596ee7500477b993b8"
account_public_key = "00b996640efa9fcd637d221f9ca51ca36c499616bd9307318acca3976eedfcc8a5"
protocol_public_key = "00d11040a8d1ba3751229b68c3a5ecd559222ef40614eba38f12c2a51523b34820"
dkg_public_key = "60000000054834e0ff49b93551e84ee15488980ff587e50c531a503d5e67fba85c0241520c5d94ee9ca81e8096e13013c917f502ad3741017aab691e7d84666f101a07527f4d8046ff3d8a9490cbacf3602abf77ffbe6a4d3e863c093b120838b1392a94"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "88.99.199.86:26656"
tendermint_node_key = "00a492a6b8ffba90d800f9fd3a220333b4e61d24cf6085ada60f01d3858d3f1f29"
