[validator.Galxynode]
consensus_public_key = "00c59f02195a41518e2defa4a991a44842896376955ed1a77a64cfc00fe5529790"
eth_cold_key = "01037727a1f5225a47407c7446119aab54414b0c9d5c5d3f60338899d260d6c8a2bf"
eth_hot_key = "010301b7c9bb78e9fd0ecf3bb8d9b3672ca2d0a4d918b7574b6957521f578bd1fbc9"
account_public_key = "001519d9e99293ad4e2513430546276eea812a492a42de10683be6851fe38ebd6a"
protocol_public_key = "006fb63f1be23e53b518ce565c26403257c22ff44681eac34f9eedf69ebeee6bc9"
dkg_public_key = "60000000bc4ef2a939df0ba706a32535f01a554ac99090b5c47f9d0ab169ac28cf4af7f66be00b581cfe929d2666290377db510899a3e4e5ffecbcb56a908eedebdfbd764488608f7a0ea3d33d6fc385441baef78456d41c77beda09ece85da296b3b097"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.90.162:26656"
tendermint_node_key = "002efee349c813577d148069b594333da4974a40a549ec4b3bbc15df385be58db1"
