[validator.GB-Validator]
consensus_public_key = "002124bc6b78cf0cf83c3a044ffa4c7d7db7aa8df2460fb6b446fbdbe29027595d"
eth_cold_key = "01034b05383e80582191959bb1c753cf78b78c2116d616a1b0aad3b8e4a06639884f"
eth_hot_key = "0103e52d545b585b36e494a56d4a772bedee7139beeb4304b61869094c42414f992c"
account_public_key = "0031eaa10be90ec153d210f2c241fc661c1b94984da1ebc20951d7ecd4c114e73a"
protocol_public_key = "00ff3f4ea2f8792f968177ed426ea40ec66f0e353d2696368aea8f9f949e6943b6"
dkg_public_key = "600000008bfb5f77242352b14f697fffd683a6b9474464da93e9b4b0cda0538821173b991f7e6f3be4d6f583511d2e712fef281498ccea97b7ebe4f0820d49fadf63c9d6a271c378c79683be717297b8d737e8e509e89e19e8446afcf292742319249693"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "169.63.184.31:26656"
tendermint_node_key = "00551e55a6f98b3e5fd7a381bc978b7f5c454d4178f0f76b75dc8f62fb326a95c1"