[validator.hedji]
consensus_public_key = "000724f0a9ce6237ba76213d1d440cf9d17cd1901f232a882621e21df7589d51df"
eth_cold_key = "0102cea67ac196f9b6d47346bc31746df562abb8e48b24888ff4560dd5eee0625290"
eth_hot_key = "010203a58df57a9af317b5a1619053bfdc9bbe2aee085274ef97bc39477f459a314c"
account_public_key = "0047ae7e25c598844d4b28cca4e86e6f2d5228989d4bcbd23215e0d86b87d0731c"
protocol_public_key = "00b0d4a03d75b437b076d86d0ded1394fc3be4fb281d5f26fb1757edcf51ffb33a"
dkg_public_key = "60000000ad59839e1e604e6ce926f130938d5caa5e0301c69e4110689949d623b2dd78842f90585cbdf4a4e13e03335b5891240654ae28a4241b43c020b9a5816e6f47a03b596d6c10bd9f51cc546ab5533c5a37a9256d18fb0c3d6a2029c7975b712a02"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.92.13:26656"
tendermint_node_key = "000eca95d156a47560a91c47e8887ba6b1c6db332f1e313d4ef57ad1e146469a81"