[validator.IrVo]
consensus_public_key = "00ed6cae36730267c530ac55763255579084e69575dd51282eb1b70a6d889a980e"
eth_cold_key = "0103868c1295e483e10a232ed822c45e92dcca549fbfb2a515a8f17052bb5eebc47c"
eth_hot_key = "0102b8e3ca59cab88b6e75f284787deca38903f403bb3c69fcf7d4b643f044c0e7e4"
account_public_key = "004c796c3a82746f9c7b8ea7e892626b6780900eb9c224160db1803feedf7e69a3"
protocol_public_key = "00f8d91b8b1b4419bf245147ec31e1bcf2594d4a0769129990e5475806903d18e5"
dkg_public_key = "60000000aebe56e5069caa12aeeb62a7f0c1e1815a4b6351855352b1ebe38dfba2fd966aba15dd1eb47c382fce2b6360adff840e3d70794da2bb8b54896a2c2d132d8a4575f553d50b216d0d569df53bfd84cf3fe759f2cc3b29a850d747555237fed585"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.21.40.6:26656"
tendermint_node_key = "000abbbfbe2566662f3594b86167f5734dd72dd58cb3d793f50699cd93e691e2b9"
