[validator.Mafi]
consensus_public_key = "0058e4c7f17f3ddd7a020c50185bfef658d5fac0036900d596013372e8bcf0713e"
eth_cold_key = "0102985c3f8fef8cf5cadcc05bf16e74610aad148dc5e667bac8c96320f0ae6305ca"
eth_hot_key = "01036c6857c7d7cce64b704f67b3073f20842a26d9f94465b70930262c691d0467e2"
account_public_key = "00ed3ddd855ba57a2cf928b7f560dc4c17a0f56ee21147cbb58b346707f6913dda"
protocol_public_key = "00758a07c3bb9865e3def73761bd2ef2781c74e90dc9a009e09c4e612ea0e7ce35"
dkg_public_key = "60000000a165f53e788f5f46a5c12aa55cf7758ad7c7537513b03d030fb0e65bc477bb53352d5169c9b14dc6cb3dc6dc2892a518cf9fbb61ea2c6ad97e2dbc059b0a38840ec2aa881aa2b440502001fa6aa020e67ad3ad014a3179b80658f132d110c206"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.231.238:26656"
tendermint_node_key = "0002568d8f295439a4f57de1eafe310ddde17a46b4f249c6d8bf783d8fa50b8f6a"
