[validator.Moon]
consensus_public_key = "00074c1383fa376dea9862121b75255b9549cea83181038ee37654f35133bed567"
eth_cold_key = "010365f1fe06d3a77c0cc7c0c06291dfda62186c23e45b6a84dcca238fc952af538f"
eth_hot_key = "0102798a296dd03b600f301295e7453f8240ef72aeaf7a6825cdebfd65010822ce6a"
account_public_key = "0031809c80c0c79f08e74e064446bc8afcd06f8a08cebc8f065ecebe9d7b171a1b"
protocol_public_key = "001140667b9afa6d52ac14e65af66362c5fca8f309718ba5574b1d52a92671a906"
dkg_public_key = "6000000032a5ad55524b603a4b6c5ea383bf24a2df5249bd734caf3d847c7aca96ad69e82575a468f4195910b91faccc379adc0a867483e7791a80ef8e76ed2f9400bf165977c699429e104b6adcb9540598e8066b4adad6b32c160511393dfd39722391"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "167.235.102.221:26656"
tendermint_node_key = "00db86accbd97f65fbed4fe210b2c91ea965715832478100c508204557168646fc"
