[validator.newton.zone]
consensus_public_key = "009f5e3d38c4f6d1b27155f5fb6f77368104496335ca15f399f9f91c913e568e49"
eth_cold_key = "0102f77bd72f5940cc5c716a932f5009bbead7906f04dea342938a8acf32ffef26d7"
eth_hot_key = "01035da576cc1d0f93308e3a7df577466f44aabc224e7adc768dd33db91f778cbda3"
account_public_key = "00b30cd165000820f64982fc45d1aa1cfba60a1bfa5a19518f92a91f1e83418824"
protocol_public_key = "002d2b023e6015a4da95ad2f243834776610de2d835e2513f301b5b4472f5969b1"
dkg_public_key = "600000009fecb7d0e231521be115cb9d9eed40293a13348cbf9cb458bc3496d28e8d5a6727cae900c34d2ab45eb0457ee4a459192e610bbcb6fe36dff9192cf3cb5ba7ffe62b3fbbfa41783cfe61b0d46d4650988c5b7f28063b3184e8b5a613934d8f80"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "157.90.183.32:26656"
tendermint_node_key = "00d2a26e9d44ad8cdcefe804e258c06056979efdad3671690e27c34de477f0b73a"
