[validator.Node_Guardians]
consensus_public_key = "00b0684b7c5701a273c0037de69fc8aaa79af5afd17572583da901f93081901167"
account_public_key = "0048302dc42d756a89f99ebed2ae7a4b366e20de3429a956b282e865efdf47c51f"
protocol_public_key = "00a65af2a3ad67ce09f78c4d878ffb6f5eb191088c14a969b7ed32db8a042a5fbe"
dkg_public_key = "600000008298bdad9eb977d70f169d270da78078a9a9de77b7ddc2e451be9722298172ec1780de86186ce2449addbc3fae74530b65ba9a787f93bbdbf947b300cebefcab9d42c19e377e17d19c2e3ffac23da7a3c109959df203e5c2f70b521ee9976a8f"
net_address = "51.89.43.174:26656"
tendermint_node_key = "00dca58acdc36b659af1731ac893e320a24e5f8a9a2181c1e051cb994ab5b7a94a"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
