[validator.nodeADDICT]
consensus_public_key = "0095f6fc7554d1be655ccef80b57924abc61e64521d84bd5cb62035348b53c9df0"
eth_cold_key = "0102c2a6e4abcbe80415c2642c3ed7098c655400f9b792cd5fce8b3afedc484b1ca7"
eth_hot_key = "0102704940c03649b668122bffc5b4befd30af0251887d544f7233859cb48ea46d83"
account_public_key = "002fa280c359607584b08ce41778c3ecac55a2863900d38096068bd79657543f90"
protocol_public_key = "008dedf8f551e7f03aa584af63fa52f92426b90391c9fecc123922c1fc277e408e"
dkg_public_key = "60000000a4fa58d9a400dc26f9d59f8d29fb7be194e998ff66b60df1788802429ad41b719846b156614f8b758ad48accb05db418910e932805ece7c83949431788d128712ae80fe69dc4020b57fcbad9edfb00350efc7a32e"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "92.255.176.91:26656"
tendermint_node_key = "004b37df155e49664a82ce82d680f514c40871a8950afd1839d8ed8662c74690cb"
