[validator.Oldenzel]
consensus_public_key = "00a0e8d696135798260d98f2f6a5f54c43e1f78ec61672ea932a46cb7464b9bcf4"
eth_cold_key = "0102df4eb0f5f54df0014a472069746be5a73325d424e21737cc25369b5bd0af1f7f"
eth_hot_key = "010223ce829479151abf02a85029be9f4ce15bbda7ab399a3a099b1c28c3d998dd8d"
account_public_key = "006bbc6e72412a482646c2644f7151e44a8e09d785434ad25d855d35583e200b8f"
protocol_public_key = "0026af3aa68ef0e45e1c2e7ea84e6fbc5f4a66adc5f3b399db7673b9c003d4f94c"
dkg_public_key = "600000002a57cc216cef6177e975e63820607d2985211ae0039b24ee3a0a0fa0a4989f273b2c9a798f018e8ea2ca5b7c21c8c310a01ed5e45048dbc7b50f8a4f6d648e42aea26a0d501711dd0e5527f4fdf453bdde8d1f005bfd94064d470bc953da4989"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "23.88.70.109:26656"
tendermint_node_key = "001e40704bdeb52effd27f6355b2cc79c5c410bf216461b5bb53de29569549a122"
