[validator.SBB]
consensus_public_key = "002e9ad10786cc7e3aa5c89f8951ec11cc108055451c79760e17bca05ad4547e57"
eth_cold_key = "0103ab3d7daa9bab2b279c7f234eac776d178e00f8a6290e64b3a3739cd2ede79a4e"
eth_hot_key = "01032a6e09ce7cfa26d7863fe877c96dad345cd460f7b9e403ef0f594e1810ab52dd"
account_public_key = "005029d2894f93fb0bae5b6c7aa38b63c0f1d3efe1e95429009a8c4c6814cb0289"
protocol_public_key = "008bb66da8d4899769a260924f10fa280dcfaba27ea010d1d95f329202dc6b3401"
dkg_public_key = "600000003594a1f949637b868c8ab9bd1a278d91c7a0ecd3af1944c002f94b095de76af605778ee1b4e58a4a3f1d094aecf253064c43f64639a3e8ac292385a0985e17d2606f2967ac355d9e7ca0cce3bb69bb60ca053ee23d71bd74e956193cdd8d4e00"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "167.235.53.127:26656"
tendermint_node_key = "00670b73b7d86d8da541c590c502518920878aba5728289c01eae443dfb2805518"