[validator.Stakecito]
consensus_public_key = "00a7cb5073ddef80f339405e7f75554f8ae2176caf2ea5eeb4d1efcbdf141ab3bf"
eth_cold_key = "0102161f8cd7c7bf82f56f7ae7579b44a34f4c6b67c485b77cbdd29fb95d27269ae7"
eth_hot_key = "01026ca10ddfa318ddf4ee3aa2896003abbb683d404fc5744ee4133b42268336446d"
account_public_key = "00d2e66e624928eeaa2439378198826d96cedb1574c57c4936179bf48611f81c5a"
protocol_public_key = "00e936d8a6936a4ee4834726875bb24c1205b2ee445c4ca3ae13703bb93f749ab7"
dkg_public_key = "6000000054a5f9832f4f6c22a0d6164fa18778608e6eceb9f336daf08ae02d282a36de4df2ca25bf1cfa033e862e76ded5f2231538d918009c6cf40a0d7c452134e2a735d65d99a6b920ad9e0c49862c78bcfda49913b619c1ba1bcfe2b14fbe7430f680"
commission_rate = "0.05"
max_commission_rate_change = "0.02"
net_address = "51.38.53.103:26656"
tendermint_node_key = "00142dba8dd760844c5cad2af2503550b06a7980bb201c1b0b19ae2f10175bcebe"
