[validator.StakeBroker]
consensus_public_key = "00c4bacc3b836d93adb23e498561edaf0a5f3eec58c3f5c15cccfc03a7e1df496c"
eth_cold_key = "010337c35a346f6fbeb182308eebbf0544da5a725b390298a3fe44adbf8dc04ff99b"
eth_hot_key = "01026c8aeeefd6ae817303619a170e04fba2007b0ffe14bc1aea686f3fd5678d73cb"
account_public_key = "00f98a9b2268f6cfbbf129611618f4a02ec120b451171b9eb082fbc3663d433658"
protocol_public_key = "00deffc2bf5b96ef1e6c87c0b39dfd6eb8f7bd00d06ca1d03fd0c60503cd2d9a74"
dkg_public_key = "60000000f01abf4112d86de928a723a732afe0d62e342f3fc10fbba3dafe808f070880d7dd95472dfa43fc6f56832777ae01bd094755e33ce30e9079b0fccd0afc01b11dc533b4c0566420531779f790564b63e0ac1536fc30502ae5b9f825365832508b"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "45.88.106.15:26656"
tendermint_node_key = "0010cff0a480be948bd54b8713951091f86728a1a45ab4ef759545a63c32cdd56e"