[validator.subandono]
consensus_public_key = "00142b6a05ce5b08256bb0cdff1f4a2d86686adc419393a1c177e9f9be6a35c8b3"
eth_cold_key = "0102f6c4d5825901d74d3d454b3c65e1a8e703cce1080e9e7c39b0d60184cc6a9bed"
eth_hot_key = "0102b65ff8f286256076cb28e61b7fa7d65fd6c9af196cd5b2fae3083053c37c9df0"
account_public_key = "00df9979c0df0d27de689b16f8a5e335aaeeb1db1dff67fe9a7c18b7d918d18783"
protocol_public_key = "00db266496f089e8f6b2d7c538824aa01eaa884dd103fba1a96c6513a7509eb12d"
dkg_public_key = "60000000dc04851d6c2763d7bb7ba6702c1df5de30af306a46c4bd075bb9702a729a28e961b370b49c1ef8798e7e12a7c5185815929eceb3e1ff49ce8e9295c38dbf58ec0e886bb9343b37b7d9d7c66c4f9f4661bc39191c20f0d61a8d0fb9a4aa424615"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "47.245.96.44:26656"
tendermint_node_key = "0043d57d89e12620aa0aab741783fbd161c6b083dbcb1f49dda01a040e522e39d3"
