[validator.gian]
consensus_public_key = "0064c8c267522966f2e656695dad2675719492ac229c6e95fe0c1f431899d264d8"
eth_cold_key = "0103a0b88882d390dfb01e7ec991901e5b8e01a6182cf4dc6f1aeb1e8107e7228ad9"
eth_hot_key = "010303962e13680e9cf0342d1804627c41ac1a34f05184a35ab59298e6ed1ef5323d"
account_public_key = "00851cbf7fc2c7ad04a7fa789e9b684338dd7fe22091d10036b6638ef6fc89df41"
protocol_public_key = "00785899f8937889f0b2b73a03ea745799a596af9f1ceca08932caa62b3beab781"
dkg_public_key = 
"60000000690cf90a7698dbbc3989bdd596b800fb4eae9d072b01dbc2c458e25afbd35c2a0ad56fe5cf976b5e32cd6d5ef5fdae0006b32787ededc3ee951778c4e89f4825dc3e2e03014092f2adb2e617842809444209edf74805a40fdcd131c5649ea682"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "63.32.210.222:26656"
tendermint_node_key = "0095aa9a46bd2cf99d09d28be0f2234b2c7fbff32b913cd919bdcc0fea90b11f97"
