[validator.ToTheMars]
consensus_public_key = "00870b91c3a402f970c625716b2b559dc96d359b0e4a0684b70447a0448c10b804"
eth_cold_key = "01034ad90a0ef6227e35f137394b300e8130638e318f9d8a9cdaf8384bc0ea7ff18d"
eth_hot_key = "0103e1b35da9ee4c21de42dba59b6881abc72a156590f67a0b4df1f2afba75a807cc"
account_public_key = "008cdb31d9eb38e9a9d6ab8678e3681d6c5f7889f34ca6a7e1f0d5e9e1c6e1e8fa"
protocol_public_key = "00842729495575198d8229e12cd3559589cbe8f07d08c3c7fb9bf2a2c9ffbf76ec"
dkg_public_key = "60000000379ca9799cb7a928915b099d2ad0ba24bd033b3632b7a80445d89c01901c6a0b56cb154f974120288a39f4b7d2ab301491bc6615357ca16c106024949dd9d3af074b612bb4576c405e5857a3cc5a96b825dd7020fd6c46ec65b70a25a1806b93"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.108.152:29056"
tendermint_node_key = "006b6f1510903b4e2e4cb87e2f64696f2f4351576d123ead119bf43b6dad753787"
