[validator.pucha]
consensus_public_key = "00607df68b61da775e203fa0fa38c594a7b8cc78f8fcaf67f4fc6e2958b5a7554b"
eth_cold_key = "0103267482f78cbf439f3d1b13e6e2738014cc4d2540922093df2c88a07660e2e75d"
eth_hot_key = "0102b7e2b6ee15a55948e53908f4231b93504ca6a40460627c405e908c557d265bda"
account_public_key = "00728c1c71d591c89285edcba68bfef04adafa86a120caaccc979688d037697121"
protocol_public_key = "00b9023ba30ce2baa7635e52b4570a3620f10ece2582869db8e57cf738fb068633"
dkg_public_key = "60000000c2967004c75817d48bee8a4a59ca2c49b2b657166f1cfe08fb08ee0b8c9a11143ccc6e3092d4dd70585b08d9301cab0e206549eadc3d5e2a668a115253d6fcb626345d224c7a277b79af14c9e69b543c8b7d590b065d48d8f1cc069c07b29b8b"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.21.28.230:26656"
tendermint_node_key = "006de57d46ad5f1374c4f1370f53f48303a58f1c2a988638b50376cf91dfd70299"
