[validator.VikNov]
consensus_public_key = "00a97e67a4edbf83b33847ebcb1da0e9c66567ae60da3a3a14b51cc606fda78ede"
eth_cold_key = "0103db7a1dc60e8c96a7f61e11779d12903a1484144d32c27d2ea1f9c6cfebaa0232"
eth_hot_key = "01039d9b0ee138d803fbf0b09cca692aa7d2b44ebd6adc562b1467d56339ee371251"
account_public_key = "00eb4ed766aa82a0fc9b7e0760fb844bc436b9c33e370115d20a8d25480709b673"
protocol_public_key = "004bfeed64e1076821a4e25bb54edcf21e71de10cfb66d7cfeba211a973d1bc684"
dkg_public_key = "600000001eea19e45b874384c9e1c98d4761c68d61bdd3b4d363428cfbd75f5aa8b30692b4e6a367abf2403144e08e54049e390eb978b4555cddd9c7f5dcc618ddc0a6c26672af0412d3b80d67ee0c7c3b294d9e040b08c7cd84583e3e7f6a1f2f972392"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "77.120.115.145:26656"
tendermint_node_key = "0070c612b62a6e15907d80255b61d3f672788c38322ca50af0ffb36072019f4d97"
