[validator.ZKR]
consensus_public_key = "00d0a6c50d9e2dd29d1fe74935718bf347e6a6498bfb9819a95323111136be8158"
eth_cold_key = "0103dc436d5d8c0b9e57fb6c90b0c9e3f62e80906812f665db3da8c92e632751f244"
eth_hot_key = "010364108917321179c2032605df1634a7280550e4852eef2c517e4bf027f5e8c1b2"
account_public_key = "009f2478a28c7653ebd0904fe461803ae898bcb7e6d72332e026d551bc392208e4"
protocol_public_key = "00e62c3f252de1543e44e371cd97c1ff2aa40c6043de77c68c87635fa1277ad339"
dkg_public_key = "60000000e603a4aa659e3fcde3d165de16418b8a803a296c48bd0681a597c8765a6f5b0c0d37093e22fc28b6011e26ba73e7ce0fe4fff0c83bbfe091e7b91362287fc8e94b49f7da7d9817b9b5d08719
4d2c0dfada82821a537e4b3ddf879bb0888a5686"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "62.171.161.236:26656"
tendermint_node_key = "00e9f837cd23b36bc37ae00f113f8cd372058873f99abb1cb6bdbf37ca6eabde64"
