[validator.B-Harvest]
consensus_public_key = "0099a33697a84765f69710e152f97eb2106cd558cbe64064b3a3ff4e7be7716a86"
account_public_key = "00a67983676e459c05e3675587ea4ce349314ed7a0d0ee05a8fa9d8835d20cf5dc"
protocol_public_key = "0077ef35e2c70e34456abb9673b87a8bb438b1d5b1ac529b49210064a2da9059c5"
dkg_public_key = "60000000e8a18f564bd42e76b25a9b27bffbe36257cb5087e10f8dd760e202fc6a2108cea4520e2856d7a1b7e6c89dc79300ec0a8a2f9a6ed64efd96c889f7c1a9942e122668aee0d483066e26c8b36cc7c87a6157f731346d9341bda05c5c800d3df680"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "43.201.126.213:26656"
tendermint_node_key = "0079723aa1fd01d56c4c761224b8dedbc0414362599e2356f2cbee2a136e187886"