[validator.888Tnso]
consensus_public_key = "0006dc40d12071edf23d5949b50de068cbc74e4a7f821414532b27b42d35b57d16"
eth_cold_key = "010338de2c6400a7c4edacdbc6dec9989154a7e93eb9616584763f20eb61d173f760"
eth_hot_key = "0103fdfc8e08f742ff9cda639ad95b747db6b1fbdd70a904df4775f22e577fab93f7"
account_public_key = "00cbd2ba111b9da6225fc7289c3bb338681899b63d60b05bc090806b7af592afc7"
protocol_public_key = "00ccb4e26e21a35b107f5605e8a1f8f34c4628763de582273f6166668e5b85f5b0"
dkg_public_key = "600000003652cc980cf46c937b1126b07a5f42923f4a257db5b2f3f6114da16479c08d519ea88e7b583fcba4b85d7b89dfa02616de5ce1c2b1716aae29cf6235069d481d5d014d142bd0f73000a3da561d026b030f3473b5cb74300710400e1063b10987"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "162.55.6.163:26656"
tendermint_node_key = "00cf971537c767be2dfe4adb414575ee12fa647699afcef74a086d3a38bf90c136"
email = "89686697888@mail.ru"
discord = "888tnso"
elements = ""
telegram = "@drdren88"
twitter = "@tnso_io"
