[validator.9527]
consensus_public_key = "007ca49575585b3b5adc2d757637249a91f3fcb3a5a8db549e149b028fdbfddae7"
eth_cold_key = "0103a3a30633aaffdd1d751f35d0b159bb3fe6e0d152bde830be54ee7f575fdd4a6c"
eth_hot_key = "01023839b4b7c6cd3e79a26ae6b6549b873af8dcb32a4cc26c1e64e6e3efbde35a37"
account_public_key = "00cd1d0adc290572f122658c3d578e709be8df170f009be22746100d1db71e2400"
protocol_public_key = "0082eb22bd581eea40b195b526a576934207b0a65404750927d9e707d7d223b229"
dkg_public_key = "6000000051fbbe7b1876a42ca7f65aebf6110699fbd0aff4689bd2fe59815e618337877787d0c3fd61ffd07bc0cdb5637014be020116a89dc738ac53ed98e2c562fa77968ea684b79299532f3257559f0c52bd712264724e8ff2d5fe39c9e710b900f793"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "144.76.107.182:26656"
tendermint_node_key = "00993510165e6768d6e27eefb35d9219159636fd11741b58d5606660a26db2230d"
email = "gomerflinkt@hotmail.com"
discord = "_implorea"
elements = ""
telegram = ""
twitter = "TerranceLouk"
