[validator.cryptobtcbuyer]
consensus_public_key = "002fef1ecd78a423ff94fd92768b556c05a4fe8cfd1c64db8b993a17461b52bb20"
eth_cold_key = "0102bd464363d7a992c61b1bd64c96ec050c1dab756c9bac93fd9af1e3b1a4af0cf9"
eth_hot_key = "01035354a3f423149e61ea47a2196567436948f99650b346704e1c00333a8bc5e3da"
account_public_key = "0018f2235029bd8650436d6bca036b783214a335386dae520d131d80f05670d289"
protocol_public_key = "00ac1bd4251bf899f5e743d636744bad44a8952a01e02afd1b2fedd325ce60a76d"
dkg_public_key = "600000001177c5d2e443f1ed0d0b424e26598a1497d7701c7c079bf043138fa77b4f389f7a8436e4d9f3d4017f653534f05e0c177a8232d57c413ffc06ca0ec8ca9bbe05584d35c7089e972207c9194ea6e3d8e831e5d8ff50d8681fcb867e29ab304781"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "194.163.165.176:26656"
tendermint_node_key = "0048dc09cffffd4942f23a9ebaa46cbec47f8dd6f52c56898720e1ed1931679a20"
email = "cryptobtcbuyer@gmail.com"
discord = "cryptobtcbuyer"
elements = "@cryptobtcbuyer:matrix.org"
telegram = "@cryptobtcbuyer"
twitter = "@crypto_pro_1"
