[validator.Firo]
consensus_public_key = "008c62e9d524d1939978e86470b4312ebc45c51236768bc79a6e5cb3ab23a98a62"
eth_cold_key = "010296b02813c04dd6778dbc7b9fbf78b64fc88fcca2448df400b76dcb51b0198dd1"
eth_hot_key = "01029c554704ce29aa623e928b64f11c055bf742c1d6a1fd55a0b291c9bfc44b55a0"
account_public_key = "004afb66507de4f4124966506cb568a35cfa071b08decd27c28e45be3f9d594fc2"
protocol_public_key = "0012b5af1879351905e1d66d2671792772fcef136a594f0cbdbe34d0409d205d4e"
dkg_public_key = "6000000004fba5736b03e504354adaadfc732a49e3e42a42de2bc73c8717e4852e046ee14cdda291429d1272eac3749180505919b3efb203677240410008aa73282b4905ebe9056823a0c0aa3b9928417c8cc2e8f6a8bcd00a090e226a7fd57fb1165c09"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "194.163.148.115:26656"
tendermint_node_key = "00cfa9d284a77b7a74512ba09b7ba701d82bbf7e7e1311d292c4fc786b222a98a0"
email = "f352200@gmail.com"
discord = "firo1200"
elements = ""
telegram = ""
twitter = ""
