[validator.HashQuark]
consensus_public_key = "00ea706c6e50c92a24d0f6822bc5ed07ed343c8b45c83a1a10dd22fe4dd6e0e4d4"
eth_cold_key = "010212007c24f06ec9bbfd55a2c135a0f019754399bc8d63a86cdc1d5451a1098933"
eth_hot_key = "0103239615dec3ea4ab891b872601a159d7396f9049170ba613803de2e72ac6d1a53"
account_public_key = "00fabb4965199768de7e135094c509b6228210a5afb20a9b4cb53c829f2cd22259"
protocol_public_key = "0074b141f7561d6dc580f9928e0c3e2da07cf1b1978b3206883cde41e295ce7ecb"
dkg_public_key = "6000000029e9823f35cf2dd12b1fca0abccf82b7294f796737170819380c15711e426ba6b9e01d449356d70d47ae92b39809c503d7f909b38d349a9496c4a94702fb2c584ab8c6fbf1f9f53f09d265bf86049c1f21615652f075b78ae0d4da7fa9b85c96"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "152.32.192.85:26656"
tendermint_node_key = "002b52ee467a28f259e0c90411c303deec52c3ff8606abb66f993afb8427f8e4b0"
email = "wangzezheng@hashquark.io"
discord = "Fern#0389"
elements = "@hashbamboo:matrix.org"
telegram = "@FernChen"
twitter = "@HashQuark"
