[validator.JeTrix]
consensus_public_key = "00aa64c88395932a635f0fddc20ee6d43ba36b5ccf73777bf9ee78b929884f0b18"
eth_cold_key = "0102a1ad4ab358d4f9bd0f9b2e27bb701b6edc38925a6e4f304ba2abd376cfe80c32"
eth_hot_key = "0103586c0067f1c8a65427c6724d01f6f510ee7d53b54118dac56e105d03a4f54bcd"
account_public_key = "005d06a0afe0df76e33067693a151af6b2753131d0b89f4a9835e2e249ec8a4f35"
protocol_public_key = "00ff3af1a38bcda487cce67b2f3324412494e5e4e81b45974ed6a42ff2ab89b29f"
dkg_public_key = "6000000054e0f95c0117560615f0bdd86393856908118dce58deb7a1760414edc07af6fdd29e3209b89233067f24c88098624517a44eb608f05fbdacf2009c9151acda73c451f182c62c185a94d2193480e29451260e8b4fb715dab663c4bcbaa679ba95"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "85.10.198.169:26656"
tendermint_node_key = "00470a6b2efb287aa4ae83e4ffb4b1675754f942a0f887b061276bdc552e65a066"
email = "ilfats559@gmail.com"
discord = "jetrix"
elements = ""
telegram = ""
twitter = "@je_trix"
