[validator.Kelpie]
consensus_public_key = "0017f8cab65f819ed632c1ecf777d5cdcecc59e1489beafb72a19c3e05877641d1"
eth_cold_key = "01026c8a683df8e77dadf86e3e40b577a893f6cdc73443773725803c1c365d9e816a"
eth_hot_key = "0103e7893a259eb5daf7fe89e2c4909750e02de0c52074098b5c6883b84fae2e1e35"
account_public_key = "00b91e147203ae5bc9644727c4bd4a39c8bf9da86fde74173baab0a260b4489045"
protocol_public_key = "00100800a14add813cabd6258a50f077c37615d27beaa637f031a43fad4de25fc4"
dkg_public_key = "6000000076c857e448c3723aa531f203b066892d1557b138354a6349865017a47370dfbaafa0efee2022f2023cd9254f2ee84a0d67f3e2b3979767fec7f75c7dac00e0f8754d67f89039e2e85dad0c96e99a56b690728a3496b9e96aa991fac316beb584"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "144.91.87.99:26656"
tendermint_node_key = "00d35d710c9c7faa65a7036e3945d6e0d555f38807f6c78d291fd96e51bb0a5190"
email = "kelpie26rus@gmail.com"
discord = "ke1pie"
elements = ""
telegram = "https://t.me/kelpiess"
twitter = "https://twitter.com/kelpiees"
