[validator.maragung]
consensus_public_key = "003785a400c18828ffa3e0c638e81773a2de5aced2a9fc3d5dfb9f16cae4d98616"
eth_cold_key = "01038c0b83157ab887d091518d1b05f30497aeb5d1dc95f326803e32322ae94f8b09"
eth_hot_key = "0103b6e1010cee9cdca598f1ab5477971510c5da1c38e18bb84fd1f532cb0a35eb80"
account_public_key = "00f8d914e5f5d5cd589ae56c575b3729149bdf143e34b4558d9893f837cfc644e6"
protocol_public_key = "006f5d273ef060cb7a5e696bf1f9e64cfd47e42c3436606d7f91a0ce5bc4ef7870"
dkg_public_key = "60000000fdf51bd5120392bdabc73561526bb1efefc2abf49d54e9f7bf4065434f3a24cc74986e2ac6c480debeedd9833726d8067d116d0f1d8b0a1040e34e37a8b35a1471510452b681b0dfe34bcda18c136779988136e6d919c9988e88a4017fc59d03"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "109.123.238.97:26656"
tendermint_node_key = "00107cd12cc752e1a94f3921f5964decaad24a29ee3d8b9adf5efacbd832d5fc4a"
email = "maragung@outlook.com"
discord = "maragung"
elements = ""
telegram = "@maragung"
twitter = "@dewimaragung"
