[validator.MTnode]
consensus_public_key = "00798efae6ca106a8d4aa4fc3b91bdafd6826c067c0b89d1d452943ade53f4ce5a"
eth_cold_key = "0103010eb0a22983f630ccd3026e1d6fcab253d6940d1fdf72b7b48559a48bfcb9d7"
eth_hot_key = "01038876ab779e167f04a701a990c53c0ebd21b631afdffe6364dad8b55e5f22c755"
account_public_key = "00197c68d7b92839e1dbfcc75fca917953bcc0d24893b8d53bbe9ea28e55843aa4"
protocol_public_key = "00c4c8b8f07d29d6b7c721e959cc28444444c725b1659d352bd551268bd6562366"
dkg_public_key = "60000000d53f5421c8dadc7a045db5288e9ef60c36ecee90970f862f76fc3e48b498d8d5ef4387d400afec86ffccee36def29b05eb5523b19e21cbab2d7d4750d0c03b6ffd6e58beea4c8a2512dea744babe316df247e96f8cdbc8fd26684b5be70d090f"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.140.109:26656"
tendermint_node_key = "00975eb3857e7ddba8a19ec85a9bc8ce815358c4464ae274c839465e18380c55eb"
email = "choioff@gmail.com"
discord = "MT#5364"
elements = ""
telegram = ""
twitter = ""