[validator.mus56]
consensus_public_key = "0062c48d34cc5a9b111fd781e9ac90662982de050d29947e5a6eba1caff35cf678"
eth_cold_key = "0102429f044d5b17ece9a5927bd32c9a0ff79ec73357c6a12f62de1336e9d341598f"
eth_hot_key = "010342ff79c7a91deec84d7edcf4f9e6690c2681110c0679061970328ad1ad9a1eae"
account_public_key = "00f9b7e3db94983a194675690c12ded18d17be841e09720a7b8a103e6f276d5262"
protocol_public_key = "005fcf449d9d7e7975349275040c631257e38d409dcca7bb00977f9bc05fce1ab2"
dkg_public_key = "6000000085ca2b68931da5319f45f9d0937df4232334465818451039e3d22f7971d2cc14dc5413f9d776eb860062bcfb84ebdb0f5b6dc426ec0b2db7d860c2e75ab7ef0caf068484d9b28515fe686bcde9473f12501a204cad212d50ca49a50997d3070d"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.43.51:26656"
tendermint_node_key = "00f041ddac6b993949dfc9b5db2708fbee7452be0aca29b1656ab9b00ad47edd27"
email = "mus56@mail.ru"
discord = "vladislav7137"
elements = ""
telegram = "@Vlad_Fe"
twitter = "@vlad_fedchun"
