[validator.openbitlab]
consensus_public_key = "005dd452405e4a2495bedc20c8728f15e19eb1eb05c95d315c746cd5e76e88ec9c"
eth_cold_key = "01021822df5570e9d97747ddb6f75af39650c017e62ff660876c00b96e3d84b9c968"
eth_hot_key = "010220b9f3e65702b663eab91888e8b8c6c10ba92b4998c6bb5465760d16d0bf4c82"
account_public_key = "001369354b1fa3e8f99476a81777961f6d106a13f99415f6d1564f4e1aa651d3b7"
protocol_public_key = "00e6586296bc1955ade27c9c6d99a0c51dd353305524e258dd93e67e0f0c695a96"
dkg_public_key = "60000000fae66f74a7ad697ce8340212642f0450dd5cac4c90be7887aaee2ac64e5422658879d2518eb74d885e53542248b4c80d920a462adf3ded72a6f7c81945a59c2cda7ab5e1cd6b0eec4f66c4bd525f1795c37d7743c92724dbfdeec084630a4384"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "178.63.184.133:26656"
tendermint_node_key = "009ff3c01eb14d52e277f558f9d93b53a1d646f465e14b6549624e92365bf7a0f2"
email = "openbitlab@gmail.com"
discord = "lu191"
elements = "@lu191:matrix.org"
telegram = "@lui21"
twitter = "@Openbitlab_node"
