[validator.p2p-org]
consensus_public_key = "003059f26301a2242567ec3655f2e012b602ea03f404b568b6c949f5d894d3492f"
eth_cold_key = "01020e633f9a96e4f15a92af8e70e12e6362d5b8e9943454a58e79b9bc20fe525fcf"
eth_hot_key = "0102a79b8d652e3a9780a63b275d796859c20946257ab9259cca9e59b3ca35f0020f"
account_public_key = "00084addee5a39338c73e3eeae35fbb94e7fcee0cdb7870e57cda3765666eff453"
protocol_public_key = "005e7ca9b02d2072dd3a1113157a112421490869e7dc49ad918eb56a1011ac97c8"
dkg_public_key = "60000000f3f610f1056c5f3e3c0b8aef7b5d2dff8ea53d1e6e9b3e231a810803aa616a4ff4ec02049db284807802c3916cc4d507376999a01624c1e5813091d3a87dfeed30687f98dfbb7a885519458df4f046d32aae441fe4695073bdfbf6206c1e2d08"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "rpc.namada-testnet.tm.p2p.org:443"
tendermint_node_key = "00abc244427e4d17a3a9ba885da6490ad113dba1401e4626e4b7b47de52fa2ba16"
email = "cosmos-security@p2p.org"
discord = "frodo_p2p"
elements = "@cosmos-security:matrix.org"
telegram = "@fridrixnm"
twitter = "@P2Pvalidator"
