[validator.Robsberry]
consensus_public_key = "002317558e64c9e69c5db317135298ac17e263be8770e277e6a1edf34744474faf"
eth_cold_key = "01023920501d5cfed820e6c924a851f498b80777f613235f162b545019e8d81e8d42"
eth_hot_key = "0102b5e72fb9d550809badfc938040762e00fab801fda7e39b68445669ed4b5bd017"
account_public_key = "001085857bd46e36fa18a51f08b396eeeca8bda502b88d8767bf31f3a6f3073c8e"
protocol_public_key = "0073ee1a2682705ef0b54777fe4e6f09ecbdf050c93c89eb3105aeb657c5b37fc9"
dkg_public_key = "60000000c190183002a5c094055dafdb071bffaeda22ba004e9c25fa387d11be96969359601644abd9461b0ed4be6f209a7b0a0a0df35e5dcb19ade36bdeb0a1d984e38959e5e2c3410d59207dae1eb4122680fd399ad216a0022d6505490a95ee8b840e"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "5.9.61.120:26656"
tendermint_node_key = "00ba5fed01f740faf53f13fd3bf92c5ec65122217c4516bab2d98cf2e8f03a79c1"
email = "meldevariata@hotmail.com"
discord = "robsberry"
elements = ""
telegram = ""
twitter = ""
