[validator.stakrspace]
consensus_public_key = "00d0c65d2d9bcf63a10c8e87bab5835b2f4a4093c0954bf9a1939caa053e0a91c8"
eth_cold_key = "010317f2c0e190d9f18ec2ab1dcb5f227eeb872d7c1e4887adcf56b1cc3993fe4891"
eth_hot_key = "010373851c08519bb754832ddc81ad35d2ff5cac4ec2dec42051731601de5136d64c"
account_public_key = "00b0dbd945c48e33cbfa3923d825aaf4767100a7cf3274c29e30a6b58254b504a1"
protocol_public_key = "00c16773eb209eeae623984b6796ab781e8dcd6997ee3931615c7c49091d67625e"
dkg_public_key = "60000000f1867e286a5caa47391ed07b4873e62dce055d0b1859f73ad5287aaccfa2770e5bdedca70583b9ae674da97334a78105d396323e061c595f9e1291f48547e49c6260c1d97b09013ba246fe481862e339d747206b5d10de9d5441310795778b16"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "142.132.152.46:26656"
tendermint_node_key = "00db38ff32addeca47c86e5d8e42c1377ca703b725f136ad5ce9e21a0f5f6135f4"
email = "stakr.space@gmail.com"
discord = "stakr.space1"
elements = ""
telegram = "@stakrspace"
twitter = ""
