[validator.staker-space]
consensus_public_key = "00d3596e05895985dd0beeb163fc03c01d4d8df5f47a670114a778b455af3e8256"
eth_cold_key = "0103d3b962931bd7f28e66bd392279346730353d9769afbd73072cd249329165e116"
eth_hot_key = "010380b4269adca234fbe43e3d83d41bb5435965139add1f0c3904f5c77ee9edc0fd"
account_public_key = "00cc2c54e84ce6ebd05c38bcb2133bd1bbeb025f240934cdef5dd1fd3bd8446b9e"
protocol_public_key = "009d03a509260f6f28fa4edb3e65260469d574a3e6af28e329812fc0777a5a1e34"
dkg_public_key = "60000000fdf0b8298680d7d3b048c3b682fbc55466c7917e2f3b2c742bf7e4981b51d886f8eeae07b86c27be264dd981d271bf0339778a985a1ed8af68554715b789b441e30a1abf42b80eed3da1ab90e7b2995cb8253d155ee12492269bd6054eed6b0b"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "85.190.134.38:26656"
tendermint_node_key = "00665563cdf48c46faf89170b4c7d6450be8bc16766ab1e63d617c94a57cb86004"
email = "su@staker.space"
discord = "sustakerspace"
elements = "@suley:matrix.org"
telegram = "https://t.me/Su_StakerSpace"
twitter = "https://twitter.com/StakerSpace"
