[validator.Wetez]
consensus_public_key = "0032f6c7e83eb8c5acffb3bad566cb51e855afb441ef4382e0ac13cfb1d12ab539"
eth_cold_key = "01039c2f08cfa777762c8fb6202f6c74c2217a1914e132f7f4d68956f5ab1603a56a"
eth_hot_key = "010250745c8a398b981b25e01a58644b763ae678513e2534f2c475f7f7c93588951a"
account_public_key = "00d5c5c04bfd3adfe6aa3d63baaec078d21cc966e8797f129fadf609afe69faedc"
protocol_public_key = "0013333a5708538dbfc99bb85cbb83047737e46884fb4b86d84f2354a786b2a4ca"
dkg_public_key = "6000000048e177d32de8cfd8fd1fbd220f238639234f01ef8ac44e6fbfe7e8fae49ce54cee746193c3f076b65b13a4d44575130dd4d463abc7973bbd1b4df3ef54843176f877193c778862ee008c42183420566f1504d647dfdce6c7caf39e467262e80c"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "178.63.105.179:26656"
tendermint_node_key = "00d560cea863baeddb704b7db2acace32ad353ed4a907f6dbce8b30d6efe3c8a01"
email = "merlin@wetez.io"
discord = "merlinwetez"
elements = "@merlinwetez:matrix.org"
telegram = "@cyber_doge"
twitter = "@wetez_stake"