[validator.kokos]
consensus_public_key = "006eb5c95dc6419aa2b430fa6b519440450a63fd5f837da90d537556357dc9061b"
account_public_key = "0099be9ab70b8b62ecd156d11a8aea73f783542661e914bc6b2a02a431f442fe63"
protocol_public_key = "0002b618240726c0da85f80b872035b3e963e3a94009a6e6957e1f6a99548fd216"
dkg_public_key = "60000000fdd80787d3898c0d98f5050a107a3a70e301f5919389293c17484cd7465712defeedb90953ff8e726fe9d90d6a0b600e889e5958863ac9db60f3c6bbf91008e6538c68ee869a926d4c3132b085c0d4c00dc326dff147de8f790d0a4cb63c6d11"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.21.141.82:26656"
tendermint_node_key = "008d065ce83ab0616b36a6114b7835e54685dcc0c9c58716250b86b317b13ebce2"
