[validator."newton.zone"]                                                                      
consensus_public_key = "0028bc13297d8617b0a6fab9a4631b337f8198bd0663ceda28ff724ad483ff298e"
account_public_key = "00396c8b120d9405cbd54b1b44987a34ff839a9e0e86fea4f9582031d9eff5e134"
protocol_public_key = "00001466ee471076a845be0da26c6ec1a3d145122171c6e5f715f4e4f7115696f0" 
dkg_public_key = "60000000e8c10020338090576c37c617582d7010f9548d8429be84fd00186317699214a59b8d5fbb8acece252427d879721e8d04872da949e8c3c891e566618428362ac9803a709b6b2a57c9cf57288a51e0f21b4ef2512cf480b32466a427f894cc4188"
commission_rate = "0.05" 
max_commission_rate_change = "0.01"
net_address = "157.90.183.32:26656"                                                            
tendermint_node_key = "009b0b71b5a22189fa8a752d6d7e94898ec64ffafc68208a0d023b66b461cd45c9"
