[validator.agosabe]
consensus_public_key = "001ba395e0a435d14182daba69d01a2ef60622664d4a0d1d4186d13bb55411ad72"
account_public_key = "00ed9ada97ad5d39f1531cd2f33e907efe3109853fc028928bca20c08974ec273d"
protocol_public_key = "0004db434a28ee98a9c321cb1aa74387178a37cc6ee216365b49db6b4dd617bac8"
dkg_public_key = "6000000084365b873b5164b20216ef77ac3f9fc4011d4038d73b2043578b51c87f76563aaf7c7d43e6b11cf1a53a3aa5781918084748cfe4385abbaa638642537874a5c55de5b308f662a9c5f37a319bd2d8fe482f40c87cf597b4eaab402819a36edf96"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "164.68.102.10:26656"
tendermint_node_key = "008adf175a49144f8d4248fda05ed4eeb20a7ede32450cfc3ed3a83014e8d03fe4"
