[validator.Allnodes]
consensus_public_key = "00e781d1f817174361cdcefe580e2b573f6ad58af5b036ecf6a9bac5031da1ada3"
eth_cold_key = "010304cc3bdf831f42f9930d44400fc610c806669b4d54b23cd7ba5b77dcc63cde32"
eth_hot_key = "0102946a10c390d9cb30f7783aa6e8607bdb7f4169f23bc3811c5d79bed20fcb75ed"
account_public_key = "00d666e981b29f2efbe1404a64f88952523366e5a7c0c950b5b30422e5493f8873"
protocol_public_key = "00048eb7faf72dd43d818050ed3ee2e0b4ed1686486b0885d290f9c773d24ac72c"
dkg_public_key = 
"600000001ccbecfaddd22a94f26ac606e0b022b72e49a773f04b2c756bae414e20202581bffa28f072618e5ad88467015b2638046f15a43ed15fd75d608df69545d132a12140c7c6cd9e3cef1535c698478b3afa9dd35154b0d37c22b76abd1d41c2580b"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "174.138.9.147:26656"
tendermint_node_key = "00aab62866606a5bdd53c13795b5e80ca9b31f14e1d2fd53d09d0ea220bae9ca3f"
