[validator.Anonstake]
consensus_public_key = "0091c6f58654f0fc345303c56dbe26ae559e20730865a8ff8ea08a02d747478e2d"
eth_cold_key = "01034d5eea425f5883d2b8993a068940e0d27acbfa3eb83b624ebd5bac1061dbd4b0"
eth_hot_key = "0103f530a44b7105526039756f9beffdaf4d95c6a036698e7dea35fb903d5f4019e9"
account_public_key = "009e608ba447a93559f3b16392d3d888bff5eb1ac9bf47a7b1f1b8bdcfe7259089"
protocol_public_key = "0008620ae6c9d55c88572daab1fd6b8f3eae2b6f2283dc757f0e5632150d3bd601"
dkg_public_key = "6000000030c59f5147bd6e3cea7592f16c4b78ffc4080168b39e823bd4ddbc392724413643759bf949e7fe678885975ed84fc9124b6cce210e10c5643278a5759a0efad70639d778c2b8e61aef8b526b53b48d29c31904221d46663363c38e8570425e82"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "31.7.196.10:26656"
tendermint_node_key = "009f11de7ebb1138a40a89ddd705111a9fd09e0cf64218e7d85987bbc97c22bdbb"
