[validator.CroutonDigital]
consensus_public_key = "003e0f592c5a4751cbf364922415164daa165820ae34969e1c011759ab58c7fbf0"
eth_cold_key = "0102523fc68c6b463c28544c5a5506f83f54ccd10aa32f760f3803213b112abde02c"
eth_hot_key = "0102610749ee90221d4ee908679a2af7fe7ad64dee38d78802c005df54fcde72ca63"
account_public_key = "00a3f56a9bdb852399c6c9f95e28f2234151e14fabbef8c10cd9d5b954717a9d65"
protocol_public_key = "00e4cfe725ee0054eb6e1a8c807b64d1ac9846e99d758e785d22e8654786f92757"
dkg_public_key = "60000000194fa0dcd81f3842716f4f4425525c8d8e06e68ed0e94987b2b6f3cacf2ad605b94442e8b6a4d9b863b5078d91019e0e5f61f421799f65d9e1fff6013eda31d645ecf1661349bc56705611c95aa4a60fdd09cfb19d193393707fc1fb58dd740b"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "65.21.139.155:26656"
tendermint_node_key = "009097723a9dae5cb1f13a303fbf63e9390ca8c924cc9c27c134ed966677821328"
