[validator.Fego]
consensus_public_key = "008263cb20c9a95cd716b5cd92a354b12801924365d34a2c149229412cc7488257"
eth_cold_key = "010302602ae1bd544e83a0a78fb360c18a79753541c8b170c73750d1c3ba2a262100"
eth_hot_key = "01026ad9c03a1c85ccad302cdfd3339ad0471a3c0bea3869a0d6184ac645ffa33c23"
account_public_key = "009a1286456ea9a12e4ace0beac9844fd11c2343111f0a7e7ae1172b65456df8c2"
protocol_public_key = "008aedf454b70b57bdff9dc909fc33736b4b23c8e88d6d1d6f71ed10af1d547b00"
dkg_public_key = "60000000b95c15bf1a9649673860f962263d604eae238e45c5f3fc291be691688f7369e7984d5fa9e50a457aef0a717d0b92de17e5ab34b868d331e003b4e7ec72a5db127ad9c4c3dbce477703f0b50610d336bd450d826aac1990c039ba3cdb4e4e9e8a"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "78.46.103.15:26656"
tendermint_node_key = "00c7b05af898a77bbf7239134de8c61265389a405367b87560798e55771a061f45"
