[validator.gnosed]
consensus_public_key = "0048954173274d22804f3c3f60ffd42549453c39f6da03bae2b7d9de3f99a2cfab"
eth_cold_key = "01022d5a4c70f15a0f5f8fa2b9cf6e6739bda1786fc838a5ae94eaa0e783308ef200"
eth_hot_key = "010270baf7bf2e0aca5517106cdbc5fdb84e58843b4d4f6ee471dce7d9d6face88c0"
account_public_key = "00cf27ea26ca716e88d6cc7211181c9fa447ab10b33fe73babbefd731b1fae0baf"
protocol_public_key = "0000f4f1a7602bd6fd4ef8689597492e2bb1cd409370d3358d340641f186486544"
dkg_public_key = "60000000c0521dabaca7e10d83202a445720f60cd6242f35431a61240238bac786fddaa64a941e34dc4b7f631cc6330f5db8c61903babb6a4566660d2d4d674047e66b7f61857f6dda1efa7e6250148ebcfdefa309ec535c79ec99abfee21b784768b300"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "162.55.0.160:26656"
tendermint_node_key = "0088071b1bbff5f75c163fd26eb5a7bca0728b3a588e87ce528f986b02e5883146"
