[validator.Harmony]
consensus_public_key = "00ab9a9591d316d00e67a7784a4449d2f9870ee74107babdf2ce885c77bf8b0173"
eth_cold_key = "0103341a021f08b2b1907974d70be570b92a0dbc206078f8aed01b586249fdd67cfd"
eth_hot_key = "01023c984cbd71f8e656f44769f340f14bda73c9b60632fc7778584a8af7795b5fd9"
account_public_key = "0079783854726548481572f589cb76fc3aadf00e489bc3370db1dfef266e8c7613"
protocol_public_key = "0075d915a2bb1c8e422ab6524406c78be9e91ac878205677a42040e15f030c15d9"
dkg_public_key = "60000000035a4dddcc82ef1798c156ff2e04681e5514d06b7239fb06681cd8937179cfe17536efa75b7b31dc1c5926d510f61305e38946566d55d162ad76685d0a6277c10bf0b2964b8291df85fc5572040bf56da510bdd009272446f54ba6f19131e497"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "38.242.152.188:26656"
tendermint_node_key = "00057032b9e19c8a77044f9dc87f5c0d58688c99b5ff8c6f0a8f92cf8803941a6c"
