[validator.Lex_Prime]
consensus_public_key = "00c5d9109c61bd6ad32385945d127a25a3fc55f652b1fd12bb233c7bbf4a730afb"
eth_cold_key = "0103afc961769596634e776d35164fb1d690946979941533158befa987f4916eb523"
eth_hot_key = "0103f9f554b043dbddc41d49e0f0e921786a016deda9fec0251b4df035075390d1e5"
account_public_key = "0045b854c7f4cf1ee293cc80f38eccd1218fc0f30a1fcde988166eb48dd706399c"
protocol_public_key = "000f3c6534e4b54412796e775514366de320eb99819ff2d5c1b7c349cacb9ff6e8"
dkg_public_key = "60000000e5723f42218f20eaeea58a6553ad9307469561410c782041ee2b479c3f2975d224de60efe8b15d009647fbe93eae5b13254cad4dac92f648d57e26695777b399724401c427f9d5003af7714ac186892841735158679abc3a513e641a04e1b80a"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "141.95.145.41:26656"
tendermint_node_key = "00e9a2aa9c7edc0b5c69dd69982f217b422ec7fd3460042218e32fa0addf42eccf"
