[validator.onthepluto]
consensus_public_key = "00c270627e89157ca7467ce2e44588af5fc06fe5e2b22c6ba939bc51b4ad02156d"
eth_cold_key = "01021200e1f42846ea7795fdaf3db4edf4fddf30e686cb978202f9d2b9a4b02380dc"
eth_hot_key = "01029ffd160a3fe89b37916dfccb33f2d10ef830909d93ba527f3c62ddcf480e81d8"
account_public_key = "003b51e8c5826664d13705cc821062460dff80ee6b4ce4d7083be60fbd91b3fe14"
protocol_public_key = "006838020a63c5063349b90722486da2421bfc20792523c76da39e08137e7257d0"
dkg_public_key = "600000009b4c60349b7ff8d47a1ef95f3b992df79448e1203c1026f98eddbac737d7e58c42097e3b5dd3f5f87bc399eef0e6851263bf495b2d843dba75a45bd944ca820240aaf2cbd8a1974993e27663dd58b9c751c3c0bf52a6a67368fdcc7c5e35378a"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "88.208.57.200:26656"
tendermint_node_key = "00121572282f93b97c3a5350a93d03027937528524edc0d687876039a4a70648bb"
