[validator.polkachu]
consensus_public_key = "0014cbaed0a056bd80543323b7dd87c89bc8aa97f781dd0a06ab7b3450b2f7c501"
eth_cold_key = "0102d3b9ea10195a39b23ef081c0561236ea810a08df045e670ad18fe9c2fda05804"
eth_hot_key = "0102c27dee58cde9022aa63320df20dc44a6fc559c9d02aa0287ee662205bd177207"
account_public_key = "00db52776e399c9d8e9ed365c282b981747cd5e53ce277c1643b74faba38f4c1a6"
protocol_public_key = "009f90d0c461697b9aedd682a7020e19f73f0fdb49e133955adbf50526e47112a6"
dkg_public_key = "60000000aa2c25ad412ff753115096f043202760b2fef3b60bbd2cbb14389578f2d24fe1dc09ed779c3aead6aaa1a96f06697b10109c8b6d459fee4b0970bf0424bd73171fb964148cffb06e36b4f36c75dcd4ccc06e2134d1e504d070b444e833be2d12"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.225.158:26656"
tendermint_node_key = "00d517d8e03849b0d7d0427d54927a627367746e2caaf2f8f40b1ebad86f8f07ed"