[validator.TestnetPride]
consensus_public_key = "0055f5bec4db33052c30bd94c0989270efc1623427b3f508dd47abace6964ef916"
eth_cold_key = "0103e76683cc75c72a7654531bfc7d5482e1d07b5ad0b6711a96e50bfb18f46a0308"
eth_hot_key = "0103a67f958ef05c40e166149c8d66326d024271fdcecb69d4fbbcc6ff07b3d7e7b1"
account_public_key = "00dd72b6ba3536256afcae132694cef8e831df25a8426728362489cbba04091367"
protocol_public_key = "00bb28de093179aa88f2eeac18e68532d0ed5c380d71dbebeafd66ad54c605e092"
dkg_public_key = "600000000d27cb03f96a5cf310ade0aed45e11c90859ae7859157df3f63c297629d079524df89a43e84a407aa2a3c2273043841140ad51624b39149691a2b595b86b2ff51b761e3f210b8824be4aa9f5e6a8f1e8564e0f1b51d9be6b0f1301c8cd4bbf97"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "65.109.85.170:26656"
tendermint_node_key = "00e8ee16cf370ab4b894db75a7857ef6846ccfe3b24995b5ad3adb75d9d25329e4"
