[validator.RozaS]
consensus_public_key = "0007f702a5da7dcf6a4feece656205e425a893f0b00a4da8d85e5b203e582e3929"
eth_cold_key = "01024d8f5f5b1f53a539da2f9d0730e9ebdbf140c516658137fc1733d887063ec105"
eth_hot_key = "01021b18da4beec1cfb1ffc88c3166b315a0f4ff228011f54279097b418d7b70f64c"
account_public_key = "002c8db007ca3f714eb601bcc8ff26b4a579bb3e8a16207bcc776d446d43b59da0"
protocol_public_key = "004478f7c93ccf93ad4c9ec3cafc6b4446fa090dfc1b0194b82bc5e3e80be51b56"
dkg_public_key = "60000000fe0302fd7a749893066b4454106a459b8971901f20d09fbed3bbc12be471a48934a05b890607beb37dd390f346e16204e8180f3da45c8a91a2c341d6cbd3d7b0cefafaa24aec1d7cc1f78c472e35a169b26641c326954c4e50326fa44fc5eb08"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "88.198.52.89:26656"
tendermint_node_key = "008189961bb98e5c32dc94a021d63ef17cb9cd6c9a886324cbf0281f2cd6b000d1"
