[validator.Rysiman]
consensus_public_key = "005e7ff32bf88dcc37f88881409af8b5b3857dcbe8817f0978b5adbd303a223eed"
eth_cold_key = "0103d2711fabaafa0f63b8f14e3f7ee1df4e4ceab761532f33ab07340680e8d2ce93"
eth_hot_key = "01027b1f90ec3826c256d92035e742fc7d523d405a8f2903ddcacb4d5505de32f607"
account_public_key = "00fa681d9c35a0d33944d50f8df67d3e7a5bb680eeffea769e9b4d2e3d09dfaa55"
protocol_public_key = "00c455dcb905ede0cac2f4af3d09c054cb864ed0a0bcc053c85e15b95202fa9750"
dkg_public_key = "600000002c2e0a6d8666ddf597fddd57e6ee867582f4a332fd2f3fd1eb49b947e7dd1fa82f7f78b1f858faf3d168e96e14ee1e152efabb83261bc0c52fe26fe49df10eb70ceac9806849fe8f26001c0f37c610c2733af142b9aed2f2da8f906e198c6710"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "135.181.222.185:26656"
tendermint_node_key = "00a0aa6490fac0bf3f30fbc722ccd5b372e6416c7ae8de3029fcdceff3551b45c0"