[validator.tRDM]
consensus_public_key = "00e4cb786f560a2bd26e638a11572619cc9d525392aadca6dd901e04c880a5bc41"
eth_cold_key = "010209aa5ef7b9f5235f65681901214ada68a018a9d2017f1ab24dffa4e51418de89"
eth_hot_key = "010249802826cf8abf7d9addab26785e83f57c4d98c9c7dd202fb7a81cbf2208ee34"
account_public_key = "008350267f459bb4531098c4c915510c47f281169b251b86067aa99f5d9f804ce2"
protocol_public_key = "00302d8a1d9384feff4a2a8e0601423fc0d126034d4b9310626e9c94a61e6c7dd6"
dkg_public_key = "600000008e4de6d6fd306fc5abe2b1fd5d9ec3126cbe39f540a29192d63b22178a674c41d7c58520979c708c2d978a3a9617fb02e632fc70af42f5d1f37e00ee2d1b552f5c2faf3fe36bc4401af08edc0750ca7c0e7d5c023098e0461054b27d98b94f15"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "95.217.108.25:26656"
tendermint_node_key = "0001a40284369bb01ada1cac1d592ffb698274a97b1ea16798ebd34550bdd8b534"
