[validator.w3coins]
consensus_public_key = "00de199bd6fceb8c459974995e14c8c31d2f5bb0f5d3a3149a07c394ae851c110d"
eth_cold_key = "01034ae451c1d80b541670e7db223cd0fe940d1bc6c3c1602b955c526a47b12e20b2"
eth_hot_key = "0102c7a3c68a2e82e6cc95e178eb9b1c7026692969956ef5467d074c7d652d906cba"
account_public_key = "00424cecae5ebd709975914a96988822336d4f1d891755cf8862dac4e5a7c91b1e"
protocol_public_key = "00b6c1ee94a8ed775bfd66e26b0286ba28d471b473d7123e6bf0b9fd52d605c70a"
dkg_public_key = "600000003e59fadfb2537793fb62b48d6f4b8db5fa51d1a6ec35524bc68a7bf1e63048fa866a9272a7de60f066e86346e4cc2504aa0946db5b2af8f4268df5e3f8e8b024c14f5033d1b51090b40a620e5e43a98dd4c4ab7b11452a9c567507d03af5bd94"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "213.239.210.125:26656"
tendermint_node_key = "00c7b73bdb7397e879085140eec214908defeecfc349e4842e939f20d5c43914ba"
