[validator.JamesBrandon]
consensus_public_key = "00043cd034e455faf599a77afea274d13110084c2636b3af063b332e43b4cad430"
eth_cold_key = "01039143380f88d63bd63ad9e0697082c677232f5e5d4cbc0095d69c485ab3dd956a"
eth_hot_key = "010389cf2dec16308de596927fa32db2b80618e40b53a138406a5f9c2a4dc521a296"
account_public_key = "00b2494cc3a5a99950037832157133c657154e707c8d5546ff3e457ea5a154996e"
protocol_public_key = "0094d8dcc0409fa268ef734a8a5db8d5f576a17a3330da21b4e68ce7b4d153d149"
dkg_public_key = "60000000c89d05ed8dabbfeb69fe6777f64c82f0a67a89990de459162ad3436b487b196ffc36592abcb2e2ba6e02398fc637ec01f17ad375c1d39c28ac80ff3f0c25a1b7d7617aef055384b128c64cc54d49dd097e792d216e00578a76b61f4736327194"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.21.205.248:26656"
tendermint_node_key = "009c7ae0b308134972c7b4c9b09c2c5aadf04d182fdcbba634a6073fadae6ca301"
