[validator.jasondavies]
consensus_public_key = "0006d0152a639c1a786ee364944e6c12f25f2ff5586883559e583f5141e88a5834"
eth_cold_key = "0103365f1f0a59857ab6d4b058381a6a169db88cfc99cab075b125e0d0957d5b9e44"
eth_hot_key = "010280c9ac35d213eee1adf9903ee2187fb01596443a7bb1aa70fe2fd440bf58cdbd"
account_public_key = "00ae387d83e7407126a15f867db69b7759f8b5082c0191fa8dd35579d80f03665d"
protocol_public_key = "006133b3853b76f292533fbbcdd63f023f6a11a64c4b0ef13dd674d2550ac81bdb"
dkg_public_key = "6000000013489e1d21ad9f91ac4c2b14eb024e95bb6f871831151720eb064924a41879645ca22e95eef80044e14005ad032a68044a59df11f00c89edfa0cfea4ba2914f1e0aae5314211a8de94bb537f9b0182aff364a1a81b9f8669349e342b7459a308"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "54.36.166.159:26656"
tendermint_node_key = "009c2cf07730e6af82a17d37a542bad644be389b28b6859db059694adb95508518"
