[validator.kadal]
consensus_public_key = "00ee56d6349c361efad5385d20e003c020ec8a14d9e99bec699c8018e2228bd925"
eth_cold_key = "0102896f30dc4042dbbf10aea4b0a02c8537afa770eb42ab89d280d2bb8a88a9397c"
eth_hot_key = "01034826d8b7359be7e47bc08d422548ac5ecfdab011ec3982f9914256e05fa7d8fc"
account_public_key = "00264ba2852977c33f6e39ac3476d815be701eb4edf9f452b6073d2a6593d4dde7"
protocol_public_key = "0006494bb200a9a0f3f9172b7b986aa36262dc246ab4c1037017af4253677664d8"
dkg_public_key = "60000000ab1a1358167b541b44cfa845ab744868f71bc97654bc54bf2a2e092839801544b91ad08637a717fd5c2eda3d1017db0765f7a7a01748a6ddb383c07c361c1d028f5534112ca57bfe8176e3df3944e5b6132e76d48140b3bd474c9b763f6ee000"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "162.19.236.199:26656"
tendermint_node_key = "00589f7f4c1a2bf9c93a69cc76e6fe696db604351f3277f9e8c94ba643b518d2b5"
