[validator.Morecon]
consensus_public_key = "00e745a0ec0620b16814a0861b883baa5d9bd693606e10e7c6f4032b202e9a1199"
eth_cold_key = "01036aff783c6f47659d025d8132f8cb928764f6171f7e1d2214d48d94022bee8ed8"
eth_hot_key = "0103db619037c18933a040a554ee68e0748035572f7d9b7d8e8991a726fde1258a2a"
account_public_key = "00ff34bcf9f3cd7a8a433cd42ba053ae4b287b7b79f1baa42fd8e90844257f5fd4"
protocol_public_key = "005452b8918b9838b7222b8a010f99d725f30fcb560991c212087457dcae0181a5"
dkg_public_key = "60000000f93430e567f5c4f0532b6aba6edad43f65c71c26390e0ef8711c3965f8718359d63b363132bfb85750a9d46e503cd90ddfdc600aa1f6601749c3a9ff5222a09aaf70692bbc997625402409ca9b26015a17d6f35f67f0be26aecefbccef6e610a"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "75.119.137.202:26656"
tendermint_node_key = "00ee587fe491ea15cef4794fc68aa041301b463f4bbbfb9d181554ee617b765296"
