[validator.NakoTurk]
consensus_public_key = "00f23e43a30f01f03e55b9ae801b9d1b9c9e1beb2502b26fbdbce4be98e2cf5592"
eth_cold_key = "0103f920c0230c93e4e6719c1a3a827d964676d78d509a9f940f7d0d13aa729a34da"
eth_hot_key = "0103d50dad32fadf75d63b3c6daea66bb5d17a3a1d884ea91c8e261a897f3ed20edc"
account_public_key = "005392b81f508f83b8543163d063f26428d74fbd58002097aa677ba087ef51c519"
protocol_public_key = "000ad44c0093734463b92d1c1375bb7c84dc9c6b4017ad78eea166b7fae1739b0d"
dkg_public_key = "6000000040e47a039162e227b25e9f33ea75cebefa33be4caa05c94cf556e76601066a4af36a4e54135aecefd830ee008a77270ed4fb817c714367887ffb31b9850b4854b96b0fe50d2a86e0f6a051d39f519b24de607c5da64d468a322ce5757f69c10e"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "38.242.251.1:26656"
tendermint_node_key = "0092d64cabac0a3b58b4ad537289d419c9d82d6775119a247a35ea8b3e7d638f1c"
