[validator.NocturnalLabs]
consensus_public_key = "002024ad95e9587a617f1d2a103cfb4df5fc10465a73b40afd71cc498fedeabfc5"
eth_cold_key = "0102ab91241525d42b2d3e606fc3f83b692dff2bf3d8616ddf7c4a1f484fcec393a0"
eth_hot_key = "0103354b82e3a703d786dcc0eafcf21d0ecb11de9388d8f787b1ad8aab808ea98088"
account_public_key = "00a926077fe0ca03becd0f5ee285d910f5d1d00b7fd06be5b437488d1200cc7a35"
protocol_public_key = "00497604311d376db7ec9e82b7a42cb85a4fa6a2d6da8ac6a70d0ab658ce4c17f2"
dkg_public_key = "60000000a8268d4d97643b5954c8f76a639a708a1e6faf49da3580d5cf3b9ba0417102522abfb4c907d5f406ffe9b2d6bdcb3a0648c865a9c72618e6ed178471f5d49643e498e1124e930c918fc312fd5e0cd04b40f905fad19d91ed6039e2b11f978b14"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "77.241.194.155:26656"
tendermint_node_key = "007799fac8be2be85491769b44a4791c7bc34525d7d13ab10e869f99d2eedd1315"
