[validator.onfly]
consensus_public_key = "0058ac0a1a922043186f82d8185dbda6044eef407f20e8921dfe53a98d95e7131a"
eth_cold_key = "0103ffcc71fdc245fded731448fbda632b6b4b73ecfba6517f63e67fc700686b6335"
eth_hot_key = "0103d40e51e4f9cae7e484856f2e6812fca9fc8dbafce58bc33464d03a3f184d277e"
account_public_key = "00d601917c082dbf2edf75ded1b06e80efc46052866163315f34b22973586c227f"
protocol_public_key = "00515f40c15743a18483cf72bb8c2e8388994c4f768bf69cc541be47d1c12a7e0a"
dkg_public_key = "60000000d9396d12f47831f8984b4e8404ea0d1df1d2427c0d4c67f684abd7d246f81968fdb48ca407faf2df91bd4b3c78280802cf2dd5253030fe2fe9543357ed1891495624045e8b9a6cdb5ab968dc1fefd022a65c4435c9997eafa30968342391d908"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "173.249.7.88:26656"
tendermint_node_key = "0094d744410f60e2b795d60ba587768837ffa53683fda3523696dbc035aa719d48"
