[validator.pro-nodes75]
consensus_public_key = "00df28e4cac7fb0d068f3e7e0cef7b6c4b8c75bef0353c861f6cd8bf3664597556"
eth_cold_key = "010315cd2d6fc17ca5ab41725375a266dffb2aa42d447ae7eac1d4f3252311c8a34a"
eth_hot_key = "01035e4e75d92d86c539986fc8c1bc72829b587049e23bacf19856120414969f12dc"
account_public_key = "004305e442ae4b508932298626a879d18cacc3df0f9e2c7f9ca458189bf9e25ae3"
protocol_public_key = "000df5bc841e6df7399c5a82f7c0ba713fb45434485b6f2c1b6beb2fad975b1dc8"
dkg_public_key = "6000000097227e07a95843fa8916b89bb9521e0254c078f3777b3ac166ae89e1dfbf89693717b770d9f5257212c916636db74b12b6f5ead7edf0ac4a038cc48b2e88271adf0574f57f56d78f6ca1bc27cbe561eca11e5a1e56af4ccb778c13638083c98d"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.13.212:26656"
tendermint_node_key = "00ac462b93004d5e4241d9e39ffbe634b04dbb0e09c8d855d38d2467100cc56da1"
