[validator.supimba]
consensus_public_key = "00090cefdb83835b29747e6d1773a16675840a17f35a1d1d783c27c24e74e90716"
eth_cold_key = "0103888195361b08f185375216b4d098efe4ff25b970ea00fdb5fdb7fe9d81297267"
eth_hot_key = "01027cc8acb30c1b57e33a1474a19f3ef6a7f946c55946f40aef7d13adf105d3e049"
account_public_key = "0040e69344af4ff8da0f5ff36f53727ccecbd637500ffc781641e6a0d2460afd5e"
protocol_public_key = "00592e5ece95506e23a91c10d0ffa2e06fe62bc8c62cbb98cdc11ab965a6d14bcd"
dkg_public_key = "600000008d4305693ef48fe43ebde01a3600ad8949fb4ea4201154868b631acb45d609a84cca6e0999d93c330de982d386d8050fc43d92264255110e41eed712ffe8f86560a5d9691bd8c52aae865b6fd109e2fc6c5ff03c11ce11ada98225a0e0052e85"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "88.198.26.117:26656"
tendermint_node_key = "00c77d0fb957e1c462c8cd54b384d954bcf5a8494c8cb1e4623a94837153f40cfc"
