[validator.Tecnodes]
consensus_public_key = "00469447dfbcff68382d2235df05f59e5e2185f36da0e06dbdc58540ca0aebf27b"
eth_cold_key = "0103343b6e8116bf3c32892d5bf8445e9196d4b911fd57cd7f1a448350e91ab81521"
eth_hot_key = "0103f359bda5c848bee7c2db9e6166f508bc726e7801ac6732d3b06b69a0aab25cdf"
account_public_key = "009de4b16bbb891d276c7c492413752deef4efdde67ca4b6c4c201fa805aed6c29"
protocol_public_key = "003b2c0931cde8c577db964db383727db2b0e05f8ac82de1b8cb8f6a4a39e3d87c"
dkg_public_key = "600000000b9b11236239c1cbd499afd8530a279d60bf709d215401a9126f64ef1093272beda1742ff39e136e8ad361aab8ec580fd86db45690e495496dc99fb13d2dfbfb0e0044a19eaba327ca345847b6a429910652c62d95947d00261ed6d273e32886"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.43.113:26656"
tendermint_node_key = "0075cbae07694174ac780e7917f8764c0639e50abed8e3ef95f9721bfbf85b9236"
