[validator.1ce]
consensus_public_key = "00f8f7854f973f90ba1cb1f837c315259c736d1f4c6497b7eaff7a6be35051def5"
eth_cold_key = "01032bad5cf3631653ec5ad6421b4f240f6c0f20b8871aebf0090b8850c345f07f39"
eth_hot_key = "01025a9d840f7d69ef264bc0fbfffff5f6695f6ffd5fbb779a7d95785064d300f3b7"
account_public_key = "003128024a6c8fa903bcdbb8833097720d5e4540d404ac1f7ae7fa9f266bbd37f3"
protocol_public_key = "009119c8b4bc5f018498b79356ca132ea8c061de06e04206ccd21946e23e87e660"
dkg_public_key = "60000000eb30d15768c177de08d5b873c1acd81ffcbdd314e49bda48cf1d821155215363904b877a894835c496797919f7b46b145a9ecf94ca3039dd3e9df1b6a929601656ddd53e4dc9bf0522e0359b47ce710823636ded51ce5e27dbe7fa974ac29986"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.21.224.248:26656"
tendermint_node_key = "003c5648b0ebf3a3c7134141cafca699f2c60bdd6aee4b232fd3c568be0f25e29e"
email = "humantraffic@rocketmail.com"
discord = "1ce"
elements = ""
telegram = "@ice1ceice"
twitter = "@cryptoice2"
