[validator.alexit]
consensus_public_key = "004db29c1ed89dbefc2c1d17ee46ad82d2f875ec4160f4758fcb9c6b8fd790cffd"
eth_cold_key = "01027766619c5141b967e6c5ae4125c935ba2fcc1610fb45fbd0db9e1687809c6a71"
eth_hot_key = "010330f632380166812724fda280987b3c2f885d3501fa1459b8704c52990a31eaaf"
account_public_key = "00042a89c4b6febbc7e3a8a98e02fc5ed07a93111f7b6631168130178ec445a372"
protocol_public_key = "007fe8285641c5199885b70087972150585a0699b232c41b9997c8cdbc2ea917ed"
dkg_public_key = "600000009285175a19dfe37e4bbb247a56293983e9650addb972397a36416b648d1baacadb3d4bb8fd8460c6f2989babe20bf90ff14560f07f12664c0f6030f023b04684e9caecd29d4155addc8a3345bad5705f9b99dbc30d19067a4c12d056d62c5319"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "62.183.54.219:26656"
tendermint_node_key = "006f80ee30a383f91e2254621f15d5554d8e148c534ccf1eaf82af6bbe6b2569b8"
email = "alex.it.prof@gmail.com"
discord = "AlexIT8496"
elements = ""
telegram = "@alex_it_prof"
twitter = "@AlexITPROF1"
