[validator.Alphabet]
consensus_public_key = "00417e29563ac7c1d60115755bdcf45a32da4eb5dc535d5b88123c428abca71a5e"
eth_cold_key = "01024168bd1d91781f6bf8f0e4eed109ba0749803b15ab9a4521bd7d8505ba1e6646"
eth_hot_key = "0103be1dae8b4cc6b659728931d6cbd5f50064bb341bbaa2dc36736e88c4eaaa3470"
account_public_key = "00e6b430a0cb97dcb613c330a334733a22a5b9cd77028e90512b18350bc646aeb4"
protocol_public_key = "007518a9748fa636740cb5cdc7d4dc919b5f583f71b590fc74e57d64ec3bec483b"
dkg_public_key = "6000000078cd4ddd82d5b5f4e3c06fbfd7d9c9a5847f28a400ae847939cfa226d28c6be04d78797c033184bb68ff7c32420b030c95e1927d9ee9f95a8c83d314b6ed51f321a36b6d2d10acf631778eebda4f1f45e92144a724d7c7c51c0f9be84acfdf91"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "88.99.161.228:26656"
tendermint_node_key = "00a291c10b69e710883ff512ba20065e3ba372028d33ee491c5d5eb39e37f7db3f"
email = "hurasiki@gmail.com"
discord = "alphab1"
elements = ""
telegram = "@intelix"
twitter = ""