[validator.AlxVoy]
consensus_public_key = "007004717832ad0a2fe804d509d07eedc64d5427e81c1b6a9180420f2855127df8"
eth_cold_key = "0103592f8ca87156dfedb1e58c90df3a63dc3d2d694623997ec7dd59595c561df400"
eth_hot_key = "01021012d1b7fd1a38c93b2e3aeba78c6f67633a25b05f76ef323600a6cfa79302bb"
account_public_key = "002d03f5814a37f34e32291d15dec31aba38e760577c727c37cd1ef14115b43812"
protocol_public_key = "00d40d98c4213adc44b783d38da29b515e2b1b4f4a78068dea2f72ef5d73ad7d41"
dkg_public_key = "6000000095ae25538050e9932ea5b63c3a36ba638b3ac155819d603fb8ae1e8658bf2f94c2f34703254d7848423e7241a12cba17539a73e660c7a7bade0e19fe9c06b1f9f245879028e2dcd280421f28504e2813a26dab30fcebe94c0ce4f9ec32ef0200"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "65.109.93.152:26656"
tendermint_node_key = "00521a8fd90a250dd0914a492119100c7dff9bc8a70e02d4eac1e186df4ab96a4d"
email = "alxvoy@anode.team
discord = "alxvoy"
elements = ""
telegram = "@AlxVoy"
twitter = "@Voynitskiy"
