[validator.Andromeda]
consensus_public_key = "005de7d000ca349a098dc1cf0ada7e7c111400572156a13a6e20a47b9c4c2ab5bb"
eth_cold_key = "0102d5a872101d4379201237bed311ac14d24ca6d6602a5cd86bf33c5a241c021650"
eth_hot_key = "010381ae9069cc41c1bfdeaefd15f3cd1e43a2335bc78c2b447e12e5d064b79c3b99"
account_public_key = "007c7ebc825ffe91be4a4a980afaa292fff7138c526bedda47bcd9a08f4630441b"
protocol_public_key = "00e1f10c46c93fc4a88a59ae48eab06259387cdc6524002a561005ae4953d8424f"
dkg_public_key = "60000000988dc919d3e47bce7145d3c37e5e6e8e4195163a6aa72e00c5a1f0e377fc9d96cbed84709e18a900f2c7a72c1b82de151fc7f356a98dd67b80db2a968cb88e709c88c5cff3b4541d9927d7bda3364e9578b3408ffc16cd9fedf00d0aaef61e13"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "62.195.206.235:26656"
tendermint_node_key = "0023c6435b759332fd038a9be7b900a4aa7075965e4e93f4cdf3c8aeb3222ebeb5"
email = "kursat.pasa23@gmail.com"
discord = "kurasati"
elements = ""
telegram = "@Elysian"
twitter = "@Elysian"
