[validator.ArchitectNodes]
consensus_public_key = "00c7260ce832903ec2b73ca1201c4cf09f86df7b60c1cdc61a1058a5ec19c532f1"
eth_cold_key = "0102202346eac5331aada868bd96a6cd9313938ae418eabbb21b5265ccfac63f2a31"
eth_hot_key = "0102871ebea18d1d3a9abc0fa54b4397cdc0c0602722b58f2517baa9f8f99c1c37f3"
account_public_key = "00483b402a39d51a072d9a1e46a4994b586bbae04679b2646a840e28bf399e0a8f"
protocol_public_key = "00165dd4d45e423b49a4215af1f1ba6bf85bd12c6f33e195cd9ea272230066cb8e"
dkg_public_key = "600000000fd2a81d0ddf235cfbf5e00836d189fc936bcb3d40989bc5a5d7a0312063e5481808911e25c5fe328434dcc455cf0004c70f49a4fc66041ad2fffba16f9f78ba7d517fc0ae2f577f94759b892ac7ba2e5cfea0a7c28dda070e018b41f2108190"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.32.148:26656"
tendermint_node_key = "00cee3e8fe65429641907ff8b6a8274cec4af40bc0a4d27a34aef17c22b47e69b2"
email = "architectnodes@gmail.com"
discord = "architectnodes"
elements = ""
telegram = ""
twitter = "@ArchitectNodes"
