[validator.BeoBeo]
consensus_public_key = "004f61b837a9d6f9feb840f917768b6d5d9af30d8e509639c695e6ec0b35eba041"
eth_cold_key = "0102a447b2f0f2ee7c38b8756b0b8f3a0816f6c4f905a7cf7f4c05eb69f9c548ef83"
eth_hot_key = "010254e635ff6ba029331cdd19e835a5e4d26c94d88a7f6d1c0605e809a2f51e021c"
account_public_key = "008ce9e10ec43734bdfbfe7667e8b46eb702d4353a788d22421a58b3e33629a938"
protocol_public_key = "00a59b81a77ff8a95ff151675cfa62b9d42be529d59f206d71cfa16dfb896f50c4"
dkg_public_key = "600000002c9db59167b44f288df9157c1781be37f6813817a1dfb6b1f32e6d1fec9fa8130a12b4e8e877393aab8a33bf8964820ab5527918486e343bef68081c672b90cb52a1c0b86f66a1eeffd2faabefe69059e1d1077d8aa895a96c0347812fc3bf84"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "103.214.22.161:26656"
tendermint_node_key = "00ced744ee99b96a27a759a7771cc0660836c7fdcf30a13ec25207001597712ae5"
email = "huynh.huuha1988@gmail.com"
discord = "beo88.bnb"
elements = "@beobeo:matrix.org"
telegram = "@bongbeobeo"
twitter = "@HaHuynh1988"
