[validator.beszedin]
consensus_public_key = "00bde1b7e9d32697f7cb98761d3980c938469010429de9b815f8d14bee94616388"
eth_cold_key = "01020846165a937861d7d3ffeb24ab3e6cbd286ba053b1aa4d3d7de669e7ceb18827"
eth_hot_key = "0102754b53c278dd1dac6e23110785fa6593c5cfbb6c7f87dc77f435e60ca51ff159"
account_public_key = "00b3aee3a592e5eba9117d0d89a533edc7e3d0c41a5a4f37242a100bd99acd45e0"
protocol_public_key = "00ce2be23ae1614ef7d1cbe8c658a060d327bdb9bfece85603e448306d0b448d38"
dkg_public_key = "600000003cfc1f660a86092a50da33324fc9583da8413b5fdeeaa9d553c2fe56f5ad672a89fe948f371917b0c5d6fa5b9995ef0aae062a4c52f8719e3a1d10b9de6f9f95681dda43dc5b1c08630c8d06144ff8b10160dea2dbe19b47915d31465c6b7d96"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "77.91.123.54:26656"
tendermint_node_key = "00985823816c54ea007fd91cd0451b0d48a46c69c445f840551902813f916cf5f5"
email = "alebesedin@yandex.ru"
elements = ""
discord = "beszedin"
telegram = "@beszedin"
twitter = "@beszedin"
