[validator.blcozgn]
consensus_public_key = "009b3d17e517878b08c372448e73041d299328d545e2770d5c176011dc911231a8"
eth_cold_key = "0103c506f1139641598de67e0cdf0f60e7a6e43dba2b827bb2bd8375855a42787b37"
eth_hot_key = "0103497942493e9199c0ab863c3dc04a59a63d3cff1ff7cb01fd1a68ea180162dab9"
account_public_key = "00a3eab0916d6e2e840a2b4f8858158bc1712e4bc5fa759ccc60e8d9455665e404"
protocol_public_key = "00adcd4cc5c44bd6573e5daec708fb07ed40043bc99aec435595153788d0ef2e88"
dkg_public_key = "600000005d9e72e3fb6e8b575e8eef56158b2d119f939ee4fd3ade574bb0da5dda8e319e710a224baba6b6117ed46d9ee058bf00fd2f611a1a116f7aa0c9085b65582485410cf7d0ddf664dd4f3de5385f446067880674f49835c64ab81d8881dad2eb81"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "35.226.126.148:26656"
tendermint_node_key = "00169ebc4a57e537380218c0731d77dcc490f85f30c91ae174c1dca6b8ea0c68ba"
email = "ozgnblc@gmail.com"
discord = "ozgnblc"
elements = ""
telegram = "@blcozgn"
twitter = "@dctrble"
