[validator.CATONE]
consensus_public_key = "0085cced74cec74ffa7bf5a634065afb24415efe5f4893e848348879f87bec687f"
eth_cold_key = "0102b99c3a5196320a05469d22b36a220bd6cdc8fa86dc693b34a2b3b319bad68054"
eth_hot_key = "0102d1db74f5c2db7db361443009216dc6290edbf943780646df717f6e90d28ca644"
account_public_key = "002ad6505eec308db7f6fff3dcf4e07b9dbde66e1b8b50ed3c386b329be6d0bef2"
protocol_public_key = "00ab14c5c89222e434b5187df06803c0c0b285f28261b2b4eab510d94bb035297d"
dkg_public_key = "60000000a3a2f782d9c733f14e8ec3cdf5ba7c38195bc4d224b908604cb96fac56baab969174928b710ae68a8ac755cff26bbd0069635ed0433ed8547fe39e9ba6b60fb87b936f1645be62ca75dd2199b19793cf99014a7b3ee145089c5507f458ce9903"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.205.214:26656"
tendermint_node_key = "00d9b85ca1d45f08e1c457482b6b1d5ec46a3355b5aab53324ce973a1804d1354d"
email = “kyergus@gmail.com”
discord = “kyergus”
elements = ""
telegram = “@erguskaya”
twitter = “@ergus_kaya“
