[validator.CHIMERA-ALPHA]
consensus_public_key = "00bb5c1faa0d7a9850c414c1336d66282fa78b4d504b22e67ea7a3f0a2665f38c8"
eth_cold_key = "0102ec24251a07faafeb9bfd1217910c4dd4eda0ceb4c49bb072961e69e1fbc4dd41"
eth_hot_key = "010201c92c3d752cb5cade18daadc8ffe38f83c4e102b6b0cff4b5649802e76befe8"
account_public_key = "00b12efe9e0d03935bfe2911e483fd6495a409284e15da1591c8d85f51a274d5a2"
protocol_public_key = "00c56551c57a3e0056cb9128b1d084e109d434c2e2ab737cea0d4ec0dc614fe6bc"
dkg_public_key = "600000006bf577cc37907a14377e44421ee74cb0916c9dbcac82f4d209b05cfc09a0ce0a0bb3ccfa2986781a6b7100b5f3772101f42f2c4c9dd8a9d3fa3d4efcbb0f6fefe6aab784cbb7da64c87092e029f34f02fa57491b11097cc228fbd0c5f21b3613"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "85.215.42.56:26656"
tendermint_node_key = "005b577f0f0edb46a319a448f08f6b4b0421df70ec89d2f05365d76daecb52d1d9"
email = "contact@ether-source.fr"
discord = "douceurlfdm"
elements = ""
telegram = "@douceur"
twitter = "@mozquito_"
