[validator.CryptoSJnet]
consensus_public_key = "00e38f419e94a1ecc831bcc006d5bd81ed6eabca4e11c0f4db79552cd946715b53"
eth_cold_key = "01037c65dbc10b350f425d974014c8a22d1321c9a1f3726e86f5628962f3ea610461"
eth_hot_key = "010230b4891a75eb83e1e0f75144a778d800725b5f4009ff21241d61180fdb7bd678"
account_public_key = "0099fb16e9be422b44d8f6b2a8ccf69a061065ad1d44265d174aed9836c87468ee"
protocol_public_key = "00921d30a8225fc1e24e10c4237e05e0ca5a0ae1f22bd4d2a831dc1fd585518c93"
dkg_public_key = "60000000eb330cbbb5c5c4e359dace9674998de2487b422cc02ab94f63a48757bd4865e1b385f82459a0c577519df9cc40708d125f5b22b4d82338f1d0ea87555ea641e3b06b18134c2e529e313cfa98ba2bc7b8451750c82f6edd8f6820d2de2d94c988"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "65.108.31.106:10904"
tendermint_node_key = "00fd6e2df654ea604fda8a555131bb26a73722e85cb85c3c028f876ac96fd074c2"
email = "cryptosjnet@gmail.com"
discord = "Msobh-CryptoSJ.net"
elements = "@cryptosj.net:matrix.org"
telegram = ""
twitter = "@cryptosjnet"
