[validator.Crypto_Universe]
consensus_public_key = "00c9a9b27632dfda12ba16514853bb069fa43804fc096ec6669132cf212113ed15"
eth_cold_key = "0103867a47e2c6d1b5ff4b49d7f5358c89f08cea4426d04aeae59c4ff9ab0672f1f7"
eth_hot_key = "01029820868a2a915e22ac6ff844f23f4970a878f20b6b6b96e7693e9cd78051749f"
account_public_key = "00425862ac98ac60c86d5e3843d28056df9b916da7e9d866a2c6759a21f13877dc"
protocol_public_key = "00f8bcf09cb83a10ca453f67f2f0eeab65315587b9d99c212e7112e95b36fc37b6"
dkg_public_key = "60000000be6bd8bdce800a95877a3b8c86b6137a1ac4f3f68084d1ee05e4e67601658845cb0534ed71b832462824ad81661f9f043d8553066fde6abd3e061844cb39f6530ef9c63fa0bc4865bd470499c8d904f9896aa6bf8b6817906812434d95064c99"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "173.212.200.210:26656"
tendermint_node_key = "00a21671896f71a9fe8d7d2baa6f5888c9123267194c19600a40c03a61f809ef31"
email = "bourdeaudhui.julien@gmail.com"
discord = "cryptodruide"
twitter = "@CryptoDruide"
telegram = "@Julien_Bdh"
