[validator.davoreis]
consensus_public_key = "00a35149f00dd3dc454ad2b172f540aa54f54805d38672f2c2a5b5d26605fa25e9"
eth_cold_key = "0102a6f275beaaf93bda29aa8aaa828f4d90cccd0ccaa16a4ca7eab14960a0250986"
eth_hot_key = "0102e35d430e0991dcf505a55465f26068115a9a1c92bb1aae5ac3f43a1413881797"
account_public_key = "00f7c1a3cf6cee92678793e5936292772d92f06c34e7a390d3c0909bde11e02c43"
protocol_public_key = "001eeaf5a5852db3d16a9cd52b976a67f9129735ba8137a21568a55211db270366"
dkg_public_key = "600000008a380bf6e89d55d226ecf89d832a33e530b94293af089896eee9e29c2f42af21b9be22f87bdb79f2bc7fc4efd20f6b0877fc8d0f91f39124a0f04295657aaa613af3a90869862d3520cadb467f03948c00431ba6003a54ae8d84568fccd3ed08"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.21.144.237:26656"
tendermint_node_key = "00a1a6ab187ae8313a54314900ea6d8184cb63d5f10d7c0c4a457666807bea6427"
email = "arkamelon@rocketmail.com"
discord = "davutsahin06"
elements = ""
telegram = "@Dzzekko"
twitter = "@devviidd"
