[validator."DECALI.io"]
consensus_public_key = "00f541ea3c8aba0fd9d032706f9bf349dca7adaf2af657cbe7a0a0768171e7753c"
eth_cold_key = "010244a6e83ffc0ed2a3f3a67e9c374c98d304c62242c6f484a828d53866cb780ec8"
eth_hot_key = "0102f9f23bd931da24251e755589111d4c80ee3e4f92cfc49bf37f9b5877571275b4"
account_public_key = "003b1b198dc6913a701a7067ee5677e901083907c6d91b5111be2e2ca618abbd88"
protocol_public_key = "008cfd9cdb99447ea3c5a94aa7c87d595a101e6f5153d9ff6315c6638f3be3480f"
dkg_public_key = "60000000eedb9a8e149df1b17b56107f58785c7e4430480640a1ab205709c5084853350515a9f2e3e3327b65fda44da9c0b7bf1461dc2eb08b95cf3b498b8eae27d9061f0dd1d1d104e1baaf819718c992d97d523df4f51e01fce4ebc4540e8c12f7df0a"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "24.158.14.210:26959"
tendermint_node_key = "00dcb4716c4bf04a24f0729cf8fff1cd33c6d35b07ecc670eb754206934f317e2c"
email = "admin@decali.io"
discord = "juliusdecali.io"
elements = "@decaliio:matrix.org"
telegram = "@DECALI_Julius"
twitter = "@decaliio"
