[validator.DomiNodes]
consensus_public_key = "00754050f0f8250c8de0d36f025ca34edf8946bfa81b6ee291588afa598e63525e"
eth_cold_key = "0102146cb728f12345eef390c24410f31e353235ec9cb55673f31a958af32e568dfc"
eth_hot_key = "01021d123960f14c03080a408d616264223a2e14901d3cc89e52d08587a43ede6433"
account_public_key = "00575e6a071a57d412f482054877a6233b674e099903f389c8d4580cbe4ee4200c"
protocol_public_key = "003c967b2b9a35688539167432f97648a2f63a4890d9467785b0e7469d4b14ab01"
dkg_public_key = "6000000024d86aaf76a5150988fbd418606a782caf1095ad59f07d801a07b98ff94ca037a96bccb83d0a978b1f1ae243a6ccc30011f7abe0857f1356f6722dbd306745ca2d5a58f70b548944fbacd370864f38ee8131901638a577ad5155e878457cb286"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "5.78.42.216:26656"
tendermint_node_key = "00f80366f8b69db59819df36e71e9b56300162a52d445d2e231993ef33e1f9fad2"
email = "admin@dominodes.io"
discord = "igoodvvin"
elements = "@dominodes:matrix.org"
telegram = "@igoodvvin"
