[validator.DWG]
consensus_public_key = "0048218d40cb9631d13049dacb1f7ffa607a06d72cdf9a3f8593d25e3876a310ca"
eth_cold_key = "010340a0ff48f8ed0329c530476f4b2a272215687bed2a986b13aef7e323db7dd0f4"
eth_hot_key = "01028c66ed7f39104f192e5c2a0309e207d5e62a7213d33e5d208eae71edf3cced5d"
account_public_key = "00726eb6e372748564286fb1ca2f12e6efc77855d4b877a30bfe171353f46558d9"
protocol_public_key = "00227bf2d29ca42164dacd5e1d579d4633a7ff0f04867282ba640486fed9ff9b20"
dkg_public_key = "6000000074c8ae7ee954c00a35a3cc516e0f1c794ee2ff35d087109aafd01ea3e18648a341423f2e73b8f34c6124851706d99009f3352faed80180ccf3ebc3a960b2f8ffe5bc0722548020aba133deb61d4d90059798a206d0254870991ec183017a6991"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.129.188:26656"
tendermint_node_key = "006d1c29da2dd010d0c956c3d3ee6464b255dda8e3529829ea1be811751a3a25bd"
email = "nnathantaylor12@gmail.com"
discord = "afyethh"
elements = ""
telegram = ""
twitter = ""