[validator.emrekya021]
consensus_public_key = "00824f6552a1770fe0a998a986be091a4f20b0ac23619147191e23852e35f71711"
eth_cold_key = "0103f20d267de6c3a74ed904437167d1c2cae22120fd843c75e1be57b3510050227e"
eth_hot_key = "01023fceb47727da345a1ab2e36268c9faea9ca5aa19a3c8c4a772af5bd89dcbc48d"
account_public_key = "00a88e61c76eda8a5f9295bdfd772e71c68a11386be67c23de59d3c9c581132893"
protocol_public_key = "00d791e8da3727db16a73272c17412ff054c465bec9d1ce08a8f1d5569203123b6"
dkg_public_key = "6000000056ee18df882c4f7953f7b67965f49222e37807d31a7613fe9ff82adc29db42ce37069c9026e03163b4e37f35e584480b95121d9cb04871c1095e76f32cee0f959e82a6b636616332f942a01d6c8b40414787352066f8fff562ade8d402297a04"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "158.220.125.132:26656"
tendermint_node_key = "00cf0bedabb37c01dbde5142efd546d169d201df50c947bfd3f4d49591f7cf4f7c"
email = "emrekya021@gmail.com"
discord = "0xliseliemre"
elements = ""
telegram = "@liseliemre"
twitter = "@0xliseliemre"
