[validator.encipher]
consensus_public_key = "00d7b260abf169e8b3e2aac8d94dc4ca8b3fc83f0f30aa5f230a681dc46b0110f7"
eth_cold_key = "01028e4aeabca12e46ee83c6dee1d29e8f5122ea4c7dc77881b85a72acc203830f02"
eth_hot_key = "01029888525eb5ab0f0ca772fe0f4723c8805a272c50a7d6f892bf5f30bab91d6fe9"
account_public_key = "00578185737a4d24ef2c9570f690ee9e515db661cb9161887316b9834f89a5da28"
protocol_public_key = "00a450475f027beb9794c0841e2e7493bbfa5a0ad945cee2763920019356308000"
dkg_public_key = "6000000037be94c2cca2cf3779737d8510853ef810146ee6597564970633d669f52c66f37f78cb46182f032c308d8c8cf97319121d870559e785385ee4d31b7c2f417ece46b27390eb0653e23c1082fe491749897d0b29dfca4cc603de0a148018dbf917"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "95.216.22.44:26656"
tendermint_node_key = "000ec5b03b850b86fcc4aa5002d5a57b60fc042c1c14073a1c5122662b99590d38"
email = "encipher@yandex.ru"
discord = "enbit88"
elements = ""
telegram = "@enbit88"
twitter = ""