[validator.Enigma]
consensus_public_key = "00d3bf2f41f14d4b04436940b510bdf560af2732ab223a2b1bd369bfcd91fde373"
eth_cold_key = "0103694dab99fb356be4fcd131a58d5fb676a7e93d83076879ee544b3bf5a08f4e9d"
eth_hot_key = "01038b79d48671544a04a79cf9848a130e064e03bb7620b9d30e4cf3df34b032abb1"
account_public_key = "009aac60ef1a2e408652e907d513c122d3dacf0181341785efb0a477d634ea87d7"
protocol_public_key = "00b85539e7e780bdae951b9a7e9b3c1c8622c128b3087c2e7f865b8b7ca0ad1842"
dkg_public_key = "60000000fbaef4259d25e8c2493465d58615690dafad31ce1aaa95c7f5a1fb2440ec2a0c5c3b22e43174d63c321f72ff61f9a90b05d656d9c17c00efa1458e02d070022e0053810e107e08ea4c8b2079d37df26176732eb2c84d024be9208e91321f9488"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "135.181.216.54:3000"
tendermint_node_key = "00b292bd325097085cc08fdc88f82bb2e647a0885111ac0f251abc9c8442e8c581"
email = "contact@enigma-validator.com"
discord = "enigma_validator"
elements = ""
telegram = "@wsm_enigma"
twitter = "@EnigmaValidator"
