[validator.explore]
consensus_public_key = "00d8c596b8623f66b805e11c1d4046db8d991f28ae16df709c412cd2bbf0cc8817"
eth_cold_key = "010237639d0f49c190cb1c6213616361ea1cc4f23f60f455ab7a7ac44a0364c63b60"
eth_hot_key = "0102102d0067eb17c54ab62d85da9782cea51c34ebae4bc1e31e9b9228faf33ec9b8"
account_public_key = "00708f31f2498a0f1ad362bb6d1145bb18caa78f0f0b272ef21fa3d7ae02d4e629"
protocol_public_key = "0038e22442bd50ba5fe967dbc4116a257767b80d5446c43525065f36a866906afc"
dkg_public_key = "6000000077ce686a76ce78a99da6a5f315680c05a3af77378124033c7c1369d6fd890b7c63fde2fb8d9932a2d19e8716ebb72f0248738a306ed9bd1c24a114fbdb2a5a72b03093efccddb642b4b26b419255b0d5e8f4adbbbda949666b1f3f4366ec6a96"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "69.197.3.21:26656"
tendermint_node_key = "0022563e57fc62395cbb4f6d68a2cda9721ef8d392a84ace4b8f55afe584905a7d"
email = "office@infraledger.nl"
discord = "anna.gemini432"
elements = ""
telegram = "infranl"
twitter = "@nlinfraledger"
