[validator.geonodes]
consensus_public_key = "00e326a0aaa0d056a59544b4c3b76951ad60fc1ec2a13ebc9828c3e8438723008b"
eth_cold_key = "010333472556cc35d3ee96efaf00c27aa32f74acb505c64d96ee37f606d62f455cff"
eth_hot_key = "0103f2cfc6ed8a17b75436a54f6df0db2ce1226deac01f88f2aa8e3caf77b4fb7d8d"
account_public_key = "00986f59172e24bc7684566fac03788232349e18a5db22a820a8ca7e2c2633fc88"
protocol_public_key = "000c8e312c6f1fd50b8b1780c29b13936063b81c5529b7313381b2e77c606a0998"
dkg_public_key = "600000003cc3e633e44dd9de0a63a48ab2f6969b6c2704e93ffa69bef10da37ac19cc135687973943fc388aa9ab8fa2c741dd00b66cb1fed6343a440b99d2f013b10ea23bcf6719abc39ed59bad4a375f2c46cdf8022789fb810ab6b25b34aade599740d"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "185.190.140.93:26656"
tendermint_node_key = "0031d651a289ffc7713ac4af5f3bd059ded9c046522820ad343a290a6bcf53f447"
email ="gbuchukuri@gmail.com"
discord = "ggbb.geonodes"
telegram ="@GenaBB" 
twitter = "@Boom9989212134"
