[validator.green]
consensus_public_key = "00755af04d27f6b0df7951bcc1d035e00a667b2c3c0cea7db5efa40359886fef06"
eth_cold_key = "0103b765e62561df2fb6cd2e4a471b7bc18ed52493d158b86e36d2fec168afffdf32"
eth_hot_key = "0103b34deb279ff45de3ecd4e31b4ec84425a2f8b7151991bb0a3bd96003585f65c7"
account_public_key = "005beb878c3130698fe7fa139114c5c35ecc20ecad3e2e1572aa04d8569a11cd55"
protocol_public_key = "0004eabb4a008e0b9ddcc51e67610f8df1c1bee8634e7e1a9beb1d7353c24d5936"
dkg_public_key = "60000000f6cf40bcc76051eb4a8b21fadcea6e3282020db796ca13173f1e7525a3febbe7753622c5b8d5b6bb802fcadb47417f1180b2baf5f1eeb6217fa6fe677279af367f97283d67cedf5863c2879c690e11bffad8e74c1174ba31166a3e3978ebcc93"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "51.83.237.166:26656"
tendermint_node_key = "00d21ddf6d02bcfef67a73d1dbf2457c5e1e7a9493ff2d1e36d3e93eefbd9df6e8"
email = "support@greenvalidation.org"
discord = "grunt9076"
elements = ""
telegram = "var_mo72"
twitter = "@GreenValidation"
