[validator.gugu]
consensus_public_key = "0024ff3427c8d0a3e25054666d7b6a86ec50fb76a9ff43a320b262ef2ebce04e42"
eth_cold_key = "0102db11668801b9a9d727795a64053348ba7a987b7fbe42c0b4e8cfaa247eaaa6a2"
eth_hot_key = "010270ce18351bd31d39263106d79f8ede57a0d5b062b8fd1955123ed5da857476cf"
account_public_key = "00ad0c97cf2240b5b28e673759fb6d1f3be48705e00f13dc9514db3e76748333ec"
protocol_public_key = "00800b9c558639d6d0d0100d870a921f6ee5dcfd48438f6069eb9da6a0b291ec26"
dkg_public_key = "6000000008fda79b18a39a46e563f04df216ab8f853effda8a0bb23b3c8790d80c80f41f61e6f466bd93e733d48a4912639e690fa63c2b2b8ca0555f108877db87b3c88b8909dcd2dc1a1ec6108c8043e52811348c7e3939a21ba3421cd4a1c473c2eb8a"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "185.197.251.177:26656"
tendermint_node_key = "007aac23dcc0e554ddbd78fa1a2f11e39f91c5c143335b6667ec4c75fc36b06e53"
email = "4623523@qq.com"
discord = "falwgah"
elements = ""
telegram = ""
twitter = ""
