[validator.hachuc]
consensus_public_key = "0062e793451d4b41852dbb46009efa82b7d0ca9c213a4619b4f55d7fe5242fe3c1"
eth_cold_key = "0102ea2104abc9bcdfd710d20a9a30a06463a6d2c7179f9084286a304a1345defdbc"
eth_hot_key = "010368d79dc98eaaadd85192012fcf5b7be93e51e5a2d38e1585731076069b2aabf2"
account_public_key = "00d884bd85879dd17cac336e32580001b4d8d728fbc2d3911e44a9ae12efca5db5"
protocol_public_key = "00a8ecaf5b58de1d84934869f043c3ab501a21260ce885a8b1b5e5c2e38131df5a"
dkg_public_key = "600000006367ea4eda365fc086be530c50380aed3189cc8ab2b155110de8a3938c1d883c08800e71bdd236176c82835e61281b07444468e2d544e92b49790b546d624c0decb6c3c11ea631da76c0733d41c3aaf1099fedd4d5b103148ab78eef17e13990"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "198.13.33.10:26656"
tendermint_node_key = "00543172800680639e7b6cb1d981bc4f00e30e35e61d75a771cc64deb8066f2cd1"
email = "hachuc@dongqn.com"
discord = "@titus52417hr"
elements = ""
telegram = ""
twitter = "@KylanWilsons905" 
