[validator.hunkel]
consensus_public_key = "0078a83ae93a39391f7cc0da31612279039b8e027ab8518faf0697f7d539e24fbf"
eth_cold_key = "0103856491ec77c6007f99b81a7d07b3f392578ac29cff00726721aba001dd8dbc47"
eth_hot_key = "01037942eb255166b6ddb3045b4797e61cbd0272adef33d2947174c88739080a4fa2"
account_public_key = "00a05f56b7ee90071a1ef81dc4f0e56b6da53e66c99a6e7e0ec36be032b21e8854"
protocol_public_key = "00afb96ca418505c71fcde96a2070235ffc331faf5fdc29a121873c9671ba4fe34"
dkg_public_key = "6000000002c3e6bef3654f1d4105a062442ea2b5652bc3e2de9453ae39c164b805f2dc0f42db37f99dc72cc406cfe81c27269e0e619e86ba41979be2cf02f31142b9a90c946feb1ef69586bcbcde4cd1611fa9404041fe87e78ae39b5b323edd87cec690"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "hunkel.ddns.net:26656:26656"
tendermint_node_key = "0003e94a8e5644087092388f6d9e05a8973a5e08b6ca0fb129681cfb2d1c0d545b"
email = "koduocha@gmail.com"
discord = "hunkel5842"
elements = ""
telegram = "@Hunkel"
twitter = "@hunkel92"
