[validator.hunkel]
consensus_public_key = "0056394ca30c9db331297972d263a79613c9350546e083c735e9fc5046611d11eb"
eth_cold_key = "010230be818a2d24272e50aa23acb5d7536450a7d9f030687b5c127126bddb5261d0"
eth_hot_key = "010355c19ad30e7059531a2800b7b3e5b645e7c85632884075cd1eecbfa563e66475"
account_public_key = "007230e50b5a4400fa2ba3224bc539b010a501570ef1e36c23acd02f605ffbab5f"
protocol_public_key = "009e9158fb4b3b3e1b6bc8778f2df3c35ac0c9abad01d146caf307f33969be9b7c"
dkg_public_key = "600000005b1978be5fc0f4fb9c87ca7d699e3c49590b6d3ff64ccdbcf341cb7f2578259a416a9bd088af8a7202686af4e8f128049aa6c0a7a8821d0598b462fde8116b0965f18b53cf1a9f2e22d5894fe3fade6fbd89f97d22761f1e2ab9c8ee6a96fc98"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "1.52.68.254:26656"
tendermint_node_key = "00d760db986f45300c448682e1340f66fe1d414ec96d0f04c4c1c196eeee46c6ea"
email = "koduocha@gmail.com"
discord = "hunkel5842"
telegram = "@Hunkel"
twitter = "@hunkel92"
