[validator.Ignition_Labs]
consensus_public_key = "0043ff12e6e2b981404e9718b6d14341bfd980d5a0a8314830a4a5af845caa27fa"
eth_cold_key = "0103589340faf1923198e36675335c90c2ffabbf2d62d5d6c22c69bb919cf407265e"
eth_hot_key = "01029e6fd1fca1d8ad831e06b3949df0a87a3fb44d9a36b4677e0ebdfcf6fa41f4ed"
account_public_key = "00d4b3ba7deb9863bb11748ba48d42373b75f6167f43a5d80466a607fd23bc18fa"
protocol_public_key = "00f9622b19f68e1524a39c556762467f182189cb858d46393874a473cc42342315"
dkg_public_key = "60000000ae02f9031dadedfdaef474b1585bcff83753f6c6860258e41410a05c2cade80339cca206be889a415beed9af92c8d3138f20218978dfd07a2201bc99aadc178f59acd8de9e07d124ee1f2b26c7d1bcf3e1c9f1dce98f738e12675e7cf53fd313"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.21.237.170:26656"
tendermint_node_key = "00340bc6a06bad35ec38a23bb6802e464ac79ed9edb03c43799afa9fe2a69e4c7f"
email = "phanminhthien100196@gmail.com"
discord = "holymoon2021"
elements = "@holymoon:matrix.org"
telegram = "@justpmt"
twitter = "@just_pmt"
