[validator.Inotel]
consensus_public_key = "005722d7700924114702aae18bffa02ba7066cab170a1c6b5ec5fb9aa58db02a7b"
eth_cold_key = "0103e9cedc637ae695e57d58e73f7f4baa18a95330057902735910077e6f1a52b732"
eth_hot_key = "010390a5cf0bd06448fb9e54b408c64607cd131fa16ebad57b6422b4bc43b715036c"
account_public_key = "006d863506c2dc3a169bda1de6da9990c93bfd39c68e53cb12ece3098a2ae9dfc0"
protocol_public_key = "00aa5c17b81c1e5dbf8270d542a60eb716673a28518429a7d9f0d25c8498f4db8d"
dkg_public_key = "6000000087598168ab0d043437460cdef766b9c4efc09b69e050b6ec40a3dd9bd0ea4f0fc60dffdd8cfd8e8b170aa5662710100d9d8c2863e3d60a034180d093254da142c9191855ec09171351ddc03d335974f60d742e122ad290586d16348fc1d83a89"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "37.120.245.26:26656"
tendermint_node_key = "00d2e64c01a13da477719de02a755a3c29b09de23070ee9047c25fd63610c1ed93"
email = "namada@inotel.ro"
discord = "mabalaru"
elements = "@mabalaru_"
telegram = "@mabalaru"
