[validator.IrinaGU]
consensus_public_key = "009bc70d2dc197f9ddc0b7ec0288f32ba08d86b1de43ac994f27664c8b1592e507"
eth_cold_key = "01023c107f0b673171c62958aecdb8733b1fa1cdf757bbc030fd2dfd418bb1216273"
eth_hot_key = "01025204ed7af727bdce76211a6544732032774c313bdee35b75c9a71ae5582dd217"
account_public_key = "00542b16b0f723dcf11aeda3f898953b1153c48f1511c77a195ee2ed792ab8906d"
protocol_public_key = "00c783a414d00ed649b6cdc44265f09321f4379c9e8da809242fd4904f5274e2fe"
dkg_public_key = "600000006eb92f6efe1769abc5ba5c61235ca59e3ea24b0d412124761efd3e5ed1c64b2d913e4d6197063dc4eec14e68ee273205784a626c5c503f3c277294083738909d82e1d45c06c40a3592779069cc5a1c468d8bbaa4f5fd5e62a6a75f053ecf4386"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "142.132.154.187:26656"
tendermint_node_key = "00ec33b57fb179c47e8f30122d15a9a2b6f2d6306aeb1fb23ab019defef3d5ea31"
email = "izpodvbipodverta1@gmail.com"
discord = "777anna777r"
