validator.CHOOSE_A_NAME_FOR_YOUR_VALIDATOR]
consensus_public_key = "00a72b2d30a0a39d606bd4004f54a4f7fb2c8c0c189a2749c72c43d0cba9dfdf8d"
eth_cold_key = "0103b096db076f26d5d8b65cd2cab541b14308a5893fee42847432465a741ff6e061"
eth_hot_key = "0102624d0478aa8575df5ca9a4fe9ef2ee037c4f75a21f4aa6d149e0aa74287aa0fc"
account_public_key = "007f6611c8610cd19c7b5e6539a0b7ad57a5fe61952872914b65d0ebef9e4492ac"
protocol_public_key = "0005abdad50edd3d4d02b22e54a4d36868f366055110cf348cc76553bba103ba78"
dkg_public_key = "60000000404e857c518da813ba8a3826088ec718b4b4a8594ed2bc1f500d3c5babecefdb3e4f8f5e7a76446c9c1a619fd507f314b660b8bd0a3b3e52cc646f60b1b39f1fbaddf7ec4cf2333ab8c8a5c742714fc048090e926fb906f645d16d96e6ef9b8b"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "LAPTOP_OR_SERVER_IP:26656"
tendermint_node_key = "00a42b649c111ad61b493229277b36d87c1c8883965e9893642196f1d39064a3a1"
