[validator.IsodayI]
consensus_public_key = "0010b15d8284b14bbd6d1169a0f76f36a97d816055722dd3ddbaea716787cdb916"
eth_cold_key = "0103dbbaf0f247db807c8200f38c6ce075d4dcbf0f24f5a562899ca42c38cf58055a"
eth_hot_key = "0102ff5138bc8cdb17e31672ff966ac72e06adda208e5e0b8d48fe60dae48a82c4bf"
account_public_key = "00e8d116af5642f987e995f22f7071761456dec6ca4139cab12b8e128534df1ebd"
protocol_public_key = "00cfe21e557cdd6562e30113d8e813fd1ad87e551f51623af1f594e19286fd6316"
dkg_public_key = "600000000464d2d4fc8c9ad98fc7713bdc189f40343d750e471038269af9fdca9f5206aa818ad97f627dfe2dc1fcb38b3a3e91184feae32056c6ce74b360c82450829aca60cfcbfe4f0cef9ada9b10c3dd0f49cab9f1da6338c3e1acbdd6d725c6c28b0e"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "185.188.249.62:26656"
tendermint_node_key = "009cd050046ecd4b198aa743f358925ae8a7eb38ee353da20d14a12e2107956d09"
email = “imailsen@gmail.com”
discord = “Iso dayI#5190”
elements = ""
telegram = “@iso_dayi”
twitter = “@iisoday”
