[validator.jenkkol]
consensus_public_key = "008d438b8f8abffa0536e9cf9fb81f05bd3526066d54e4e96ac85971b42c11fc3a"
eth_cold_key = "0103332cfbd2e30982994a0b0e915301a258b045ce4acf75bd95e4ce88072a752a76"
eth_hot_key = "0102e85407942647aabdedd55d1b0166a53c0f9fd414c7028291af7884146020de3e"
account_public_key = "00b3948224f3c720a43a91e9769c60c8e56777fe70d8bc23bd9b074f6771dd7624"
protocol_public_key = "00594dc4a06d50d1f65ee61bcae62c4e78e48124a1799ef931ef15c5775e43859d"
dkg_public_key = "60000000cbdd7ffb84c87023e9682f912eec59f69bdea83bd4285207ff7852e3fc9d08e3987003a3bdbf28961c2f2d013e078a154cf55b1e580482d3c3025b54c574df949049ff573e51b5b69184d8188ef7684f689039a9c33cffc681f826733dcd970a"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "64.176.181.135:26656"
tendermint_node_key = "004dc067a074345bb7e8a40e6f118fe15475cecd3afab5e9391996c4b074c04967"
email = "ajabaxixi@gmail.com"
discord = "jenkkol"
elements = ""
telegram = "zkhash"
twitter = "@0xzkp_"
