[validator.kemkem]
consensus_public_key = "00b9dd5fc513eaacfc42e13e118a9579ae67d9504ab06c4e02886ef6a54a08f0d3"
eth_cold_key = "0102efd57fb8322a6ace5a0e2be7915d10db6376cfae22e50487f0fa248dc43ddf42"
eth_hot_key = "0103a6dea45a6b9e0bb12e451ecb6f9135727853f1a2295eb51d2267e1fd59a962f1"
account_public_key = "0024e61c827fdde0aac5222c5dcf3e0233d81bb367e881172029f124cc3160056d"
protocol_public_key = "008788e05508c034ffc14e29a08fef93b612ec5411733540e599fe7d193a9e7f8e"
dkg_public_key = "60000000d6b1c2abdfc305889cc59dea35171698947174cbf8c700a4223556a74b7440351600be01cd9383c9064a0bbed974b11825aa325d358803ea81a0362b68cb8ab21289c8e735d720b48cee48302e764ba464f9658358887ef1996482d145b59d00"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "83.171.249.21:26656"
tendermint_node_key = "00e038ca68a5b0956a421d23f9249af5e04b8e37c93b93a5a0d4007acb7df524fe"
email = "lehuukhoaspk@gmail.com"
discord = "huukhoaspk"
elements = "@huukhoavt:matrix.org"
telegram = "@lehuukhoa"
twitter = "@huukhoaspk"
