[validator.kriptoboss]
consensus_public_key = "0072db48012c986996e672f87557f70c076c6a558567f3b452318228bcf2c36830"
eth_cold_key = "01028753700ad6c38229261143b20930bf9ea4f59ae09acc8927eaae188b364f2135"
eth_hot_key = "01023fe8229e1da6674d3dc1b37cb447457824daf3e57fb5aac8e7eb2a6a4e4da54b"
account_public_key = "00a72a18b2906062fb933fa9d07db9f88799a0d729fd1eb88dc7d0a157b662e4ad"
protocol_public_key = "0062fdc065c2f3c7b8aaa2c343dc3a2bb6ca9d1541eb04e498ef465c60848526be"
dkg_public_key = "60000000b0bc8a30fa79d6fe7cffd466ed7ac6524c7f7bee9525d8a7b9e6a818b49c0ef73b563f6abe8a5cf87ca4b920c31c8f03a43c378f078148974c0ddca408c4e8ef9d65664110d010268f8883c2252d6e9a291511d0b1f61ddd5c3c2780cfad7191"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "95.216.198.214:26656"
tendermint_node_key = "009426acc8b0c7bf8c67999fbd26f2ea5fa12da23e3a4bb65270c19f5cf6ba39bb"
email = "kriptoboss886@gmail.com"
discord = "kriptoboss#0313"
elements = ""
telegram = "@Kriptoboss886"
twitter = "@BossKripto"
