[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qqgzempad4wgx5enenulg300uc9t8gm7r4w4evp57skcy2lqc7eyuu9x65c"]

[[validator_account]]
address = "tnam1qy0pm6hg0zwwf3mz3a73860djywrlvudmcun2hc4"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "217.182.199.238:26656"

[validator_account.consensus_key]
pk = "tpknam1qq52mtphnwh0n7ed7zgkxpf30z070dmqz5pmzf498ckxj4ys78apzyhfegs"
authorization = "signam1qznqvlsr0nyh02xatm3qee96ezvzwfrhlykackjr9z0f4lsgk8ljaa20urvqgfd2tr7x2h50ljvcc9vc58sfdta7y8nvd7ey5namfdgr4w6rsx"

[validator_account.protocol_key]
pk = "tpknam1qr6ftn2t44hdka90ahuf0kyzrs2k3cp8ndtc8qmwv584cp8u7enlcz63cas"
authorization = "signam1qp7ehtjykn6hjjxghkdyl5xrkfy4sp4l08gu5jg0mp2236lh3eqx90sqqf9wpvl2s5ckmy7lmqwrh0kd4mxw6f8wdcry4udasfuef0gzv0vqex"

[validator_account.tendermint_node_key]
pk = "tpknam1qqudjfvflw2fzpt9jvmyjxjpc3raspqnlngaec7s0gxhvj4nwt2c5747lyd"
authorization = "signam1qp4c4c5076g9hwrrywy6vehmj9cfnrvtv4tzfa8yj9t54w95mnna9wnjdzay28axr0xxjp2lsvtqdjqpztvyqqqfyxnqfnrjnry8jecd5zxr39"

[validator_account.eth_hot_key]
pk = "tpknam1qypgzr3jf3qx0lucpdlwzue87nkmwpplrr9a2c9yn2wmsccqg8gzzgsvf84g8"
authorization = "signam1q8pldhmrw7uqpjvdqct6vp4qgas4uujk66txqlkwxjvnv8c8m54px2n5ms5elh853u7r97xwd88avz47hv7dszlxsch4u0jdntrr877aqyjmuu2p"

[validator_account.eth_cold_key]
pk = "tpknam1qyp7cjumf25ysq2s3tn57hhkm6zqlc0h576270e3jp04nw8thvf93jgv672fx"
authorization = "signam1q9524pwyev835m9k37gjzxan43vffqyzkr9ttzrpmp9rql40sj2w5c2zw6pv6xfss2vxeypum8pndelkhvgazlss4fx6gtuxy08xxt9xqqdw78ml"

[validator_account.metadata]
email = "thekit@gmail.com"
discord = "Lankou"
elements = ""
telegram = ""
twitter = ""

[validator_account.signatures]
tpknam1qqgzempad4wgx5enenulg300uc9t8gm7r4w4evp57skcy2lqc7eyuu9x65c = "signam1qraykfrn56xpf2gn49zrmn3gld4zfxw8yy6jpksv68mayqmwlfqcs8yg6jkkt9usnc59wsuctfamdt4sp25ansz8f4u7zd25nku9u0cpywl5yn"

[[bond]]
source = "tnam1qy0pm6hg0zwwf3mz3a73860djywrlvudmcun2hc4"
validator = "tnam1qy0pm6hg0zwwf3mz3a73860djywrlvudmcun2hc4"
amount = "1000000"

[bond.signatures]
tpknam1qqgzempad4wgx5enenulg300uc9t8gm7r4w4evp57skcy2lqc7eyuu9x65c = "signam1qq2u0qga3rpkqh6lzftwzm4p9w7xyumrfkav2962306mfh8nmdee7e65aqkv9vxzvlp96dkj578c5mpa0prlfcahcu59yrddm6njwygt4949qp"
