[validator.lebucheron]
consensus_public_key = "001bea1f425b39a23db35be8414132b19f3d829b9ac7f82459e39592fc53a66dde"
eth_cold_key = "01029ed32c1b7806e6b938b15269f57610f991dcdf91a15526cf32efaaffc3b49dd7"
eth_hot_key = "010201abbb57a7359d96a578894e2da641c4158e8bd539817785af73933fdaf0c236"
account_public_key = "0074770a084c68582b60f4690cedd165dc09f92f8463040be3b9602f6215601e8f"
protocol_public_key = "005bf7f0a4ba87e7e10b297d43747aaa9212d217485d9d295647371791c1184d2a"
dkg_public_key = "60000000981870ff39fb33c4f79d79d663f9018d63f3a34c83d19994e2420649659edec7978bd82cafb31bac16f8e9c13f98230429fc15d20ce5a3169650ee6065e1a901967033bb1b1b839e699fd482b01254102b55eb369667f8e92cde14cd5811dd18"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.168.33:26656"
tendermint_node_key = "00e2c305b22d0e71583e4a5f67e2b1835307e8da9a8c9273d39164ed2ba386ad83"
email = "monsieurtrading@protonmail.com"
discord = "lebucheron74"
elements = ""
telegram = "@mistertrad"
twitter = "@bucheron74"
