[validator.lincoln3237]
consensus_public_key = "00416f41792c023f1c59dfd910d297e469461ba530e1318679558dae09c6942432"
eth_cold_key = "010262f4cea15f6037e51d17747f2a69a38d38d09b9de5b9331278916c83ddf06a27"
eth_hot_key = "0103c42727bb2e859dd85448d38212973cab987ca09856887cce64680f6f1067bae8"
account_public_key = "00bf97bb93ba6ca1797fd7f6414c5c3f46ac3c7d01b8f11988c6ece69db952ba12"
protocol_public_key = "00e37f98c8862466220d89a957fc3c6d7210f869e0ac063ba5db3b90e578aa56ee"
dkg_public_key = "6000000095f171a457adeab4bfd51d76d1bb74454914fb8977a409d3e9b565b58a23213f3bcd473eb8bb2f09807dce467362dc0f3ea670d5e012aa9deb2ddff770b41c30022c21ac4b83669f32e715f43e472dfd4d01f19109ca7e093e87dfc4d4554889"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "125.212.220.52:26656"
tendermint_node_key = "002714e59d1159a7b76ff930f676e99596caf6ec68ac003b32fa42591ad079cf23"


email = "petermanntegardenervux3237@gmail.com"
discord = "lincoln.eth"
elements = ""
telegram = ""
twitter = "@VitorinoDewey"
