[validator.n1stake]
consensus_public_key = "00cea015fbf404fd7922eba1f6a4941aa00f90e9053c66fa6be9977aaa6e5cd3db"
eth_cold_key = "010212448f13eaa2c0c7bb6c158452806fcef2feff6da7d0bc024ae429c9482b3841"
eth_hot_key = "0102ac4d5da4e2c678cfca0caa53e3ac9387b59ac5679870ff170a1a19e9fc4303fb"
account_public_key = "00b25096adf092cd910165af7f046165506cb27f3eb4686823be4ed55e6869ab14"
protocol_public_key = "004676ab3458d552832400b3f357ab19e967691afb17f1464cca2cb515ca3c5e5a"
dkg_public_key = "60000000827989e72b11a435194b9901e1f361efa19e78bfa8bc5f4dbd7e4a337cb3f5ee0a4fdf93b228ccd4a05e5cda44683612d30cc964057ca81c0573d33428df4259168fe5b0a711de38eff0dc90899a6b51542273f54125b63cdca38476d3134e0e"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "162.55.84.47:26656"
tendermint_node_key = "0092ed775a68b1c8d91cc10bcfdea05a56ffc1173e45330d9ab7b2aca854040b40"
email = "hello@n1stake.com"
discord = "vincagame"
telegram = "@romanosadchyi"
elements = "@n1stake:matrix.org"
twitter = "@OsadchyiRoman"
