[validator.neross]
consensus_public_key = "00e4784cc2aff41e81b3465537d467276c92fe3a7b7860a0ffc2d97d2cee810ff5"
eth_cold_key = "0103a172abef0ce77cf9fc42fd63b50aa6c9bff29421edbd0212871afb38b57a6570"
eth_hot_key = "01030465f82b1d58c2385efa7369020692ce22488a17bff24040750df20b75e84198"
account_public_key = "00aad6f15e9378ea935509d2c977497deb9afb4c37365c188d0546ab552068816c"
protocol_public_key = "00ba58ec5923536b2bcab4ed31fc00e8d4c215c359e94457c82e63fa4c74ecd5c6"
dkg_public_key = "6000000097c058a2d0944d5c3cfc709c5abf3b87ef780d05ae78a247fcef587384684ddc2c825fc0892f9e5753cd22266f79e219d57a08c0f717a44cb44e4d18906d90d8fcbb185af7babbe7c6c4cb1025192d366d7a9bd870e6e884d37ff372f483cf93"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "95.216.178.216:26656"
tendermint_node_key = "00fb395d6d0a166a9d20ac465a85500ed14c66e1e08375831c37c341070d307e75"
email = "minhdoan13051995@gmail.com"
discord = "NeroSs#4408"
elements = ""
telegram = ""
twitter = ""