[validator.Neuler]
consensus_public_key = "00799b5cec390f93c584598f6aa303c599c0d5fa8a699dd258eaf0225c9d0acc6d"
eth_cold_key = "01022cb8532b0773138bda1a8ecbb746fa0de22a340deeb2edd4e7fba70f61cbdc9e"
eth_hot_key = "0103e62afef4000f88884e66d6e5f3d4bf5374e90a4d63d0b21124c36b28d993e490"
account_public_key = "0048d30329dfe56d8dff8ad65a53b5f43e4e924da0f5c0afe2e78c70b2bb8c3c16"
protocol_public_key = "001c86bac516947e5222a14a19f1a453c9282516466a2a4dc1e23743969fd5bc3b"
dkg_public_key = "600000001ee48139dd36cc37250152318d5825841bfd1358fa333f3ac154c47a72849d59b52f52cfb1dd8dcf273dd0623fef2614632b7b307f4401683a11529426d99b729ae213e81b8ed38ffed48849366ade354b3459563227ec1a3a53bd4d863a7a0f"
commission_rate = "0.05"
max_commission_rate_change = "0.02"
net_address = "148.113.16.49:26656"
tendermint_node_key = "007629206a284acf9866fd5238b03490d4a2b97cc0ca9fec4aba6466759558f762"
email = "validator@neuler.xyz"
discord = "minijap"
telegram = "HikaruGo"
