[validator.nirnaeth]
consensus_public_key = "001b4eb274e9d51e008ea3cc24ef028fc9761ff711e1dcbc85b66d206b9bf73091"
eth_cold_key = "010269a348b0f51112c9ca79bf94cba286fa7878349e1dc4d600845cd9d858606bef"
eth_hot_key = "010246bbd87daaaace3fa1384a764c2bcfe50e72e9202712e4517c703e16485bc28c"
account_public_key = "0095a5397ecc391a597783f43d7bb96744428c4990a4e7eef6205f09ca88cc04bc"
protocol_public_key = "007f1ae8afbc4f8780842d5fdde0cdcf9cdf7f0da9014069b6bf18b6072e425f47"
dkg_public_key = "6000000072c7d513a8995ccd07c3d464bf88fe31b1bb939fa5c33a9fe3e0fe742441228217b471f3e04058da677ff68932c14f01433d1aaec5370469040e13074262784444580efcc977f6e77a6d6f4b62394da1f8e46be3be58acd1e53b83fe14498212"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "89.116.29.62:26656"
tendermint_node_key = "002d9684a980280cf22774bd34a31f3c065c98ffdb70d8cff1e3bcd4188a98aa44"
email = "nirnaeth@zohomail.eu"
discord = "nirnaeth."
elements = "@nirnaeth:matrix.org"
telegram = ""
twitter = ""
