[validator.NOBITA]	
consensus_public_key = "00a46008f31fe9ece0f563be68d26782faf31dff206f0d88df267fc4a5cda398da"
eth_cold_key = "0103f8642ca3c7413b2b83463c8307be6cbbf6aa047d9d8819e6b52c0928b5b3ba9c"	
eth_hot_key = "0103ed37a907fab457f353bc20838aaf0fe61a23108a72fe57068f5bb4ea9cd6b2db"	
account_public_key = "00a77ad57789448bd667c38d9f0e475fb631930c167ebe96c91ca59b6ea98fa880"	
protocol_public_key = "00deae582d6edfe64decc25618e8b0afc832379e72707fd875165d14c9a020baec"	
dkg_public_key = "600000002cc7a2946c067c866378df811ffece9bd81897cc6b391c4638031f6b3252ed17e19bffd8d05ce0be2269fa3048bd5a19806fb518eb64550fa6a67099ac7d09c45c7bfe3d6126a40659d33afadcbebcc1a4269844ea05245681437b307ef3c88f"	
commission_rate = "0.05"	
max_commission_rate_change = "0.01"	
net_address = "161.97.75.200:26656"	
tendermint_node_key = "00e715a7999f732439ae068438534425bf2ef2bb2c24f8582cb90d54487c6bd3fb"	
email = "ntnguyen147@gmail.com@gmail.com"
discord = "nguyenthenguyen#7054"
elements = "@nguyen147:matrix.org"
telegram = "nguyen147"
twitter = "@Juilan_mr"
