[validator.o2Stake]
consensus_public_key = "007abcb0bfc87a0dd667f757c5029ba6ceab70573b6a5b419d2fd866bb0dcd2dc0"
eth_cold_key = "0102ed800dd1cb265724de04e734b0d9bc43a8ce11baa06b10e219220e55041e0620"
eth_hot_key = "0103eb56cd4ed3a61cce6bd48d4be58743f2b280b5eb4208c68af46fd6b21c3495e4"
account_public_key = "0084d55e60e5f43aad62a390999d729719ac562a10bfe87b3034f0dce08fc72d1d"
protocol_public_key = "001e7c28f2fae38e27c23b868218abaf5f8d28d9a3029b1246f33e67ccf448ce26"
dkg_public_key = "600000005b20829a4f3f833217f8a11c4d2a848e2094901e3df97acf22aee591186b2756fd8a79ef6b8beb9f50b187f3f1880b002f53f5d94d189ddd61aa72c5bd1ee2de2ea0afdb38e62e985c988b7b2cec0ca38e5608f08f1cbf7dae2b5fa5316aef82"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.11.228:26656"
tendermint_node_key = "00ee87c26fc2c7ea72111235a4d40b5125f0d27ecd8dceb438f19fbf68d6f7b406"
email = "q6zpk5zf@addy.io"
discord = "cryptobangla"
elements = "@timsmith1337:matrix.org"
telegram = "@TimSmith1337"
twitter = "@TimSmith1337"
