[validator.peach]
consensus_public_key = "00bacbf26052b897a3fb9abe39aaf48cbedea47297ae8e6e71aeeb23ec14507453"
eth_cold_key = "010338f60d3fcc18647da1767c4ff1512caee81d9df32d049cfc31419c080650272a"
eth_hot_key = "010287590ee7a42bec3de323dbc5d9fb0c334748e262ca34638013f4f9c90126fbe6"
account_public_key = "0027a630fc0eb6197af50f3c735908d271f89d23b26bdf91679404b138b0395e23"
protocol_public_key = "00dc90b0373851a86b4f9a6fb68c3e4480fb2cd231ab7339c09ec10bd65bd2577d"
dkg_public_key = "6000000096e79e4d69d3cc0308239b678247c672b3c886fee0a844d86c3919276515136bb4a116148f3f23bed333d334e63af2163265b79990604243f1f4c1e7a40f98890050d76c88dd13f8660685b94e203a62bb933cfa86d579577d999380453c3b10"
commission_rate = "0.01"
max_commission_rate_change = "0.05"
net_address = "65.108.232.227:26656"
tendermint_node_key = "0064ec3394ac0d8e89153afbfffe7948f318893b83af394afae5cf1bf0336d24c5"
email = "81279589@qq.com"
discord = "peachstake"
elements = "@peachstake:matrix.org"
telegram = "@PeachStake"
twitter = "@PeachStake"