[validator.Plusx]
consensus_public_key = "00d293ca7b83774e983443c710d92225cc1a7f27b3e4c7ad1e0c13150f27f77ff3"
eth_cold_key = "0103f31ddef1bb4345ca4bb9668214f9926eb56633d255959839ff082ece0cc705dd"
eth_hot_key = "0103cf10622fb3a12a2017ba8eddff3e38abcf5425fe0bbe5ae36174b990c5695d6d"
account_public_key = "009227b892d1d0ad736abd22e7149d44417b32651aea45f72be3e89d713f6a908d"
protocol_public_key = "00de84becdca47cd53a5de9ed27519c1161ee2db0253d50c5621992dbf1d9e6e33"
dkg_public_key = "60000000a84d979e30154cec2a11c0c1ebd6a546d5e262107901297bde8a002bf902c4c61c374ad41decddba76474a63922c6d1794705bd6f8aa217b9403efa528ff129777163bc2c4a112d8a51d5bd6c388977026d865bc7ef07677aecaf669fce6bc8a"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "194.163.142.45:26656"
tendermint_node_key = "00b757bb811b68bd50c2a5814cfe707e7db0db1c7191ca08ad59269580f12869e0"
email = "cost.testy@newtech.coffee"
discord = "plusx"
elements = ""
telegram = ""
twitter = ""