[validator."pulsar"]
consensus_public_key = "00ab6f139a2024866d06a9c202452079c1179115325a8758fb8e0b38e08e1b7034"
eth_cold_key = "0102a446975ec84f47353a8ebfca209f77eeb604ac80cde59b852ca8a4172ef33822"
eth_hot_key = "0102032d6aabbf038b4e8631b8b2034816503d794cd7b9bb0348699c23332b7283fe"
account_public_key = "008d7eae7f945b38723670e2d0899ff5f5d24d14987076ffa6bc064592e57c30ff"
protocol_public_key = "00cbfcd24cd29efb7534b3d3b8a3761f65679c24361b00c8f7d6955d2311b143e3"
dkg_public_key = "60000000d0a45a18a09df3ae26c867cd4846f0ee90ed088945bcb0bb16f6dc146645876d9603582adc488cf21e57ad2007b0eb1412f32cd4783e061c4d97cd4060d546ee8ca86f4907b7c390830cbcba3d8f16814e7da7462fe81e9328baf8919f6b7f0e"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "77.248.159.123:26656"
tendermint_node_key = "008a1ff2a36c8bde4aaa3cc3ea82e320da7eccda9f94a08a7e871d91fa323667b2"
email = "kaan.biker@gmail.com"
discord = "oghuz_23"
elements = ""
telegram = ""
twitter = ""
