[validator.scania]
consensus_public_key = "00dc616869710d5638c276d1d2f8a892d78ab0800923368601dfe7bf00b97bf0f9"
eth_cold_key = "01021add0e241a26b5c5ef0722500455409edb3dbdd9589c2cb495e4e6bac7dcf59e"
eth_hot_key = "0102340d6ad6e906011cf677391a32f8c540446f854df10187956a2fe3111e2cb354"
account_public_key = "00c76adc85def1ec761c8560fd9171fb5af6c8406749cb6c257c3d8ea0d9b99403"
protocol_public_key = "003411f8f11c33a158be31a9d8be365f465cd36521710c8c18bd702ba084684311"
dkg_public_key = "600000002fee54b9b8823480770ee2e61ea3c52bdd4ddac73af6f4959f3ad1488bc6129dec884f715e482d1cac9d171830a2431510a14fb8f8ff08b737e74c9c53d12b4b43df058091a58abbc8abd410d0eb6813542640dab72532794f0a0b1321823b88"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "212.51.129.74:26656"
tendermint_node_key = "00bf30d3713416c790515aca906a57f0690c3ad9b12a0dbced47a1fe198a7569b0"
email = "renato.delgaudio@gmail.com"
discord = "scaniacrypto"
elements = "@scania4:matrix.org"
telegram = ""
twitter = ""
