[validator.senol]
consensus_public_key = "005a685b7a6374ecf7014daaace2b05eb7d21d28e1c3f7e8606c14de128a28d28d"
eth_cold_key = "0103df5140c01e747602b4a92ea07a8be9f76ca1663a1c35933ec08084dfeaf04b4d"
eth_hot_key = "010237a2aaa90900f26e1f456edc04ca1e5b4b281cd8b0791a71513754491e2e44ba"
account_public_key = "006663dcc4061108686ed173822255fe50d8804d0b7c635de876cadeae2884ce10"
protocol_public_key = "002d45608eb7f8977d08772d8e6f9fc7d78f279786644729d8022b07fd818d8e87"
dkg_public_key = "60000000f3599fd66412b6783d06630d79441bb1ef4cb0b1f86d6339abd8b0b357410087b8c7ecb59a8755947aa54bf530c54b11f32b7c0069d577fbad03ec2f8f0d76a8c35672facdc998755f37bcf15cb0ac6c464b3bf85d0485f51dd5ea44eb19df0a"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "89.117.55.113:26656"
tendermint_node_key = "004fb4b6f379700aa2dd27da41afb7503da0b5d9c417a5db489bb99897644b3d6b"
email = "senolcandir1985@gmail.com"
discord = "senol10"
elements = ""
telegram = "@senol10"
twitter = "@sweden_alexande"
