[validator.serana]
consensus_public_key = "002679c242bc15e37934e4bb1db31aeae859521c0fbbf5d49c126d2c574303ae3a"
eth_cold_key = "01035baecac14bd7260af905a290bbc5bc6614a9a7e68bdfbeeef7ee42d523e61102"
eth_hot_key = "0102d61012b15bb29fc549589ef0167af5f861163cd25125073548ab0f9c19fff0d3"
account_public_key = "00bacf4c16c80c52bbf337c746f053338b4cafc607f1b52a402c8f833b279141fd"
protocol_public_key = "00a2baf9428e1b985ccda7030c9e37cd93093fdfe0af3a681d66157977d59cf28f"
dkg_public_key = "600000006ba0062fe3ed31a487c3c7ad0afe053b24694514a76bd9b62adc4e0f40c84d2bd9ee59a188c2d03cb536824d2f7ade05bfa28b3e9ab1789d7e94524b11964fdbac47c111d4e7791e1d154cb56a9ffe1046dd0345ccf8714b4ea4b8a79ea04b90"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "148.251.82.189:26656"
tendermint_node_key = "0006016df2c07f4f71dda4f5800dfeaa70c15459c41e8e336a1c168f3f87454f9d"
email = "serana.crypto@gmail.com"
discord = "serana_v"
elements = ""
telegram = ""
twitter = "https://twitter.com/Serana_crypto"
