[validator.sirouk]
consensus_public_key = "00fa267eb5af7aae1be0ab8afac01a2feda0d361577639b36d9715ab54ffedcae2"
eth_cold_key = "0103a4001b6c876f5803263a0d3053c70ef35c6de18d18d2c949c4e34411fcbea2be"
eth_hot_key = "01028045204587d7cdf2dd6c8860ac5bf224b323806960cf45a1d104d034c1cb367c"
account_public_key = "00cf1acf523494e27f2422994d35ff46ad5920b8d76193e88de6a26b99022d3e4d"
protocol_public_key = "00d477f7f7332b8a082d7917fc1d26f7cde935ff5e80aeacf38e8d096b0e3460e2"
dkg_public_key = "600000002e8efc1a4d7fd0d20836cdc7c543603b59896ef04dc4f0a1320bbf47775ec8dfaecab15c3077c196cd6e6d0bb3d518153d40421588c5bca64b85aa83d73c194134fab96b5b2752c9465484ce517c92cac68da340b3ba9c1969c517580166cf11"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "204.186.74.42:26656"
tendermint_node_key = "0058255afe13744d32993d413329898a2409cd912898875a51383e4400dd29525b"
email = "tvboxsupreme@gmail.com"
discord = "sirouk"
telegram = "@sir0uk"
twitter = "@sir0uk"
