[validator.snsmln]
consensus_public_key = "00cf45b472d93d876eebe42eb2772f515c913466dfc92eae818e453a723c7356ca"
eth_cold_key = "01038b6491cc4f95468474498915fc644720a9907bcc8c66b868d94ab7ba438819c1"
eth_hot_key = "01028ae3201400de9d5e6cc408e062be2de02c47f4b2b93733c8f102f62176070271"
account_public_key = "00d4b79a567ff7dee7f325531dd202ed3189d88f921b8e6c1f7182edb3d550fa7d"
protocol_public_key = "00a279a3b2f1a4c82bff49c5bbf7042a89548086030ce388277d61bcd86f90a241"
dkg_public_key = "6000000045f6415f455f3298a1306f23e1622c85734e0295b86b197279299c814f13eb576255fd756971d73f71e8d7c8d4428b1477e7ab062101175d7fdb061d7e7b6f8f3fcf96e4eed6e0f015dedfc158e9a626d447b475348bdb7ad05dda011f2bbc06"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "62.33.73.29:26656"
email = "snsmlnn@gmail.com"
discord = "snsmln#3128"
elements = ""
telegram = "@snsmlnn"
twitter = ""
