[validator.spaceman]
consensus_public_key = "0087a5f14f2b3e585f893fe8c18757c1951245c607465fb21f1ee415db0b7a8f8d"
eth_cold_key = "010339c2d9fa7132ab20135573199022942ff76746e75da5581c42a8300b191bebfd"
eth_hot_key = "01028db561d77bcf8599a41ffa999e72778a0d4eff8803251443dd096d1194f98fb4"
account_public_key = "00c77e98f84d945bbaece2fa618dcca00247d00b22d9d5031e0753ad5ab31e1ee0"
protocol_public_key = "008460eecc700ae585c71e8735444adc0311d410bea6a40c51cca63cb283233540"
dkg_public_key = "600000009cc860e36ba09fcaded0af28f67cc4b06bf266f5dffc6a3169bdd6cbcc3e71cf8da7dda0f1de54ae430934ee088ffe028da43963dda19ed2b5585052ce1e6d725b927acb5f08275c4e4f92bdd1de4153907d604faa9c12d72c0252048994ca8a"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "94.130.65.74:26656"
tendermint_node_key = "003adae2d61d316a626221caa0e8b56c4a5e08090741fe77c78f60af251f6b37ee"
email = "rulingdub@gmail.com"
discord = "omrgxn#2083"
elements = ""
telegram = "@omrgxn"
twitter = "@omrgxn"
