[validator.stakeshark]
consensus_public_key = "00c6bb27f9e21601a5fdf04fc77b155694073e4e70b5d2217de7fb8f9bd048f2e0"
eth_cold_key = "010249f11d9dd2f987191bcd9c27ade99a296a82732cde99ded87fbb41b06c6f51a3"
eth_hot_key = "0103758bccf969aa94b1885bbe3a9e3893e6dc93db8b90567fcd6b1911260b33a695"
account_public_key = "00faf2aa3b18b7fa1e9c29ec42461b055babc50e44950af5fe038332b0cc19a947"
protocol_public_key = "008d4823288f0992f4d7abbaa2143cbdcc8ce77c9fffc34513f63e8a7d806d6156"
dkg_public_key = "600000004115b3b4ee0ac985e8c3cece159e8f2c7aea47c6c0ae238e21fbdd67d403a4e72dc2d21fa057ff05f2dda4b9f73a8a11c6a8620923886675e36b9baf12327b534bddbda563f969d52d1f165b420bed9260c15c8b9ceab76df0da0d352b1d038f"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.21.75.22:26656"
tendermint_node_key = "00ccc8fceceadbf589ece2c4be24e0a6800452be848c3ba598c08f82015b8f8d15"
email = "office@stakeshark.io"
discord = "sizir_"
elements = ""
telegram = "@stakeshark"
twitter = "@xcalumsarmsx"
