[validator.tarabukinivan]
consensus_public_key = "00202fce973ad65ededa04924c3dcbb765b466d970abdf9f62b70b71fcf1df68e5"
eth_cold_key = "0102f9d8c9dc44a1ab551970fcc0fdc4dc7747860a28b56074ad9f84f8f13b68396d"
eth_hot_key = "0102c805ad2f2730a513e8aed86b8dcbcc5076f26f5746069f6452646943491f4cb5"
account_public_key = "006e3479965b277c2dd09ba626837398b3e361cacf2ad6de284e60fbfb9a9bbe72"
protocol_public_key = "00b7340cf39c69011b1f64ce9065a62f6e12e9d454cae20939769f5db153826e85"
dkg_public_key = "6000000076dbb97524ea979796c3081167f5de4215172ba24c848506bc2f7d48ce23443664c52981cdc57b1d29b9e07d370dd90a49152add06971ea616ec91588e134816bc2be20abc865b88a47577326d60236bd75e850673ad6c142b0248713b865309"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "167.235.39.5:61056"
tendermint_node_key = "00089e392687660821391cd6e8ad14e7af8d9ea0549a0c5b716bc2e784a701e9a3"
email = "tarabukinivan@gmail.com"
discord = "tarabukinivan"
elements = ""
telegram = "@tarabukinivan"
twitter = "@qjtze9GsNnNwHjO"
