[validator.tb210]
consensus_public_key = "0091bada379f8b29109266be856a041347bb2ae101be3dbbb37a9841787bfaec96"
eth_cold_key = "010227425da622a30f96593309366ddd670a9f55474c3c789aead9fd21ce325ec5f8"
eth_hot_key = "010239f0e4814ac48d668b35951bbdc69535015e5f7eac68c0557cf063d961557333"
account_public_key = "0063cf56888837d8906592988978dfc195ea0a05abc9d9fdd435458f82659d40a4"
protocol_public_key = "00054d46e9946085a0cbff146a41d0dfd6db9b19d54d7424f36a7d2e4940ec0ff9"
dkg_public_key = "600000009ebffeabd38a756f9d7f19d950e40530c6fba1be6ea69425b981f8c1241ce20b503be643611afc3bbfdfb0c205330d04a24bbb6b334e226cac2eb89bdf2f975e215ce29aa03d737f016a54f19cc4c36af6b11ecbd3a06f720efc18c9c119ab09"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "193.187.88.18:26656"
tendermint_node_key = "0002f3e8aa270ea3b7f4299ff857bd52ed6a66288e883ec2d064f820350a6fc448"
email = "tv.stock@gmail.com"
discord = "zealot210"
elements = ""
telegram = "tb21000"
twitter = "@stockmarketcap"