[validator.tb241]
consensus_public_key = "00f3641ef619862e91f3ba4a65fac92ff17a790937aab2709ba91ea6e13b240736"
eth_cold_key = "01036d9052bb5d30b7dc62050ac7dcf9f0b40fd321152b7ce35b58b3eb8b099e87ee"
eth_hot_key = "0102accdf5c9a5e27b38084b5a52c1f7ef0b34751afb1ae26cff8fe54fe68c256568"
account_public_key = "00596cc9aca19e63390510cdc01531f1c92f668f1a846e542a016e2f7d005afb7c"
protocol_public_key = "00673c7c77751d33e694cbf32c5482e39d6820d3aa2f53b22480db1e8ab566d28a"
dkg_public_key = "60000000d159d6f842b7a9c778a7fa58965e00afadc82d9db9f3187ca7a8f5b0a858683cfdf4be340505ed3ea07c85639ccb25019947287f4a8bc50f006730712c81ebb9d4e2e5edcb4d4f0d2b0b40a389e4a193e30ef4546410f5b50052579b0f2cf180"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.80.237:26656"
tendermint_node_key = "0013d2a1c381aa6563fc1ecea6ce9b64ed2959337f2b080c7ba289083e7bfa6c34"
email = "jjasondavis186@gmail.com"
discord = ".brlnwalc"
elements = ""
telegram = ""
twitter = ""