[validator.TheGuild]
consensus_public_key = "000640c8357a30db5703be01b84a8367deb7f9a37a6efa32dd6600b937406526a3"
eth_cold_key = "01026de6f755dcfe9337e39f4b631758716f07cfef55c43f07afaa86dbbe55a64bac"
eth_hot_key = "01023a86fd01b9b0da823024a017a41e94ff1ec83d627c66fdd87c37b3784fac4e66"
account_public_key = "00b365a0df9f4f163fe4b412739e3753df9d7240f78796958954b59c8ffc3e4095"
protocol_public_key = "00da0793bec5eb6e72a35428e25db4e4df6fbdd020d758e1f1bcec402ed1d7f9d2"
dkg_public_key = "60000000fbbe4010166c03844898b99c2bc3ca60bdff4cc4e0a1164f66a3efc79728141d73c20bcf07a72b5f92262b0b4888ce013b32069ad3977b7bcbb1c1ed5ed8bff12e804cbc1e1f496af193297bb77314a9d76e72fcda5c5b3cd91471f02fffce11"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "162.55.2.58:26656"
tendermint_node_key = "003786c34bf424ed96098a0d007c39b397ca7ba5752a72cd68be3dc1f00b0ab5b5"
email = "johgolt@gmail.com"
discord = "investiq"
telegram = "investiq"
twitter = "@nac_ibwt"
