[validator.TPT]
consensus_public_key = "00b4c29250773fefe4b8d6aee62a1018f31d39fa12459f7b39965bd213605d70db"
eth_cold_key = "010362d8c0886bcc9ab045526cc14fd1636667916f0b129c3ff41f0b64d2e8083233"
eth_hot_key = "010363901ad582afc73039b98369e465b3df206f173fc9cd78e938c2afba56e916a8"
account_public_key = "00a3e518f049690a51482d2d56a22fe1f86eb7454976f6346d56ac3f8cfe3805e6"
protocol_public_key = "0046bcd2315824b5fedef68853b0bae09ea97f322b439afc35ff4f6ec8a90f056e"
dkg_public_key = "60000000220c4c87c5630aaf9f637326087d527718ec765a7e220ee22362aaeace957fffaa83dbd712d1e22e8f551717c4eb7b066c9112ad6d67141860440e1cd76caf33727e195ba54be66c8793cd7abccddac76d02f5ea6a4c0ea9ef827437a6979d82"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "18.236.154.192:26656"
tendermint_node_key = "00766fdb686e1ff9471b0f6bb31d813fa09c6646bbcd7057c8ff2866bcfa044bdf"
email = "zeroexzoz@gmail.com"
discord = "w3sc"
elements = ""
telegram = "zozDOTeth"
twitter = "@0xZOZ"   
