[validator.UniqLabs]
consensus_public_key = "00019aaef1197fe02fde071ecf6ba6984d69170248efe74db3097e43a1f5dd7d34"
eth_cold_key = "01024f1089667d07d631d51ca2eb14c5e2c05928835265fcc660792611b877ff7481"
eth_hot_key = "0103250329c883da94248ccaf9edae95826ab595c0bc7881aa7fe323c6aadbcdb9f3"
account_public_key = "0077186aa3f48bbf60e1487d0ec07752e8237f64db6909b74ac01ddbc0050f6ad7"
protocol_public_key = "0022c7ad9afb6563e8ca51d04e9498bbb663339daf5b70bc28d1e28be145864929"
dkg_public_key = "6000000081b3c38cb934e6456c875d8f4e9c6e5e548ef1d545d04dfd287fcc19428940396a6d33d4124753a043228d101216fb0d70e74412959b45ad3a6d4c56c48a0be7a43424fcf67f438b31a41cd1f75b6f12f90bc038a639bad5ded161cf7617c109"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "82.208.21.89:26656"
tendermint_node_key = "0061ed2d4b1d8af08f71678f54bf0a0961f7cc37c6ff8a83f6911b374c8ccb33e7"
email = "erknfe@gmail.com"
discord = "erknfe"
elements = "@erknfe:matrix.org"
telegram = "@erknfe"
twitter = "@erknfe"
