[validator.Lapatylin]
consensus_public_key = "000694ad5ebb532ea156638ed42723f2442a74453a81ee3896d7f28e0e3a153fa5"
eth_cold_key = "01036198abb139504e8c2736ecbf7425ba668428c4ebbb0085162e2935ce39ab8c04"
eth_hot_key = "0103b279809bc1168ce11a242480b18e0b38eaaab119965c84ca3741d8e8f1ecd03b"
account_public_key = "00971dfe238ec934c053031c6dce8d1ae1e700b892d8bd2dd756aae32911753e78"
protocol_public_key = "0002e5965088a4d32c35f9ff0d3ff154469a7b871d3891ce8a0d8c3c2480bca30b"
dkg_public_key = "6000000016a25b9a83023a911e3e00cb2bd832c90a940415ef2fdecef4b71a32835837fbb10827c968b87c13124a4ab104085616d7e2c4a9445980023fee0477b727a383401af2f65ac741386378033b270b744c9e8516fca3aee93a50643164f443b897"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.124.121:26656"
tendermint_node_key = "00b14515dea3973726c3a9e36b59e6cb67b821a39e1c2df78ea8b5ee7dd098736c"
email = "alokhinoleksii92@gmail.com"
discord = "lapatylin"
telegram = "Lapatylin"
twitter = "lapatylin"
