[validator.FairStaking]
consensus_public_key = "007d596e74ced40ef3db001abd0a144fb32f5d8cacf12fbb9df36df60233870e76"
eth_cold_key = "0102a8978915f91cc13de697b7a7d29bd14a78de977139a4442ff629ab128e4306f0"
eth_hot_key = "0102f2ea0d25c1d85e3c2496c8a0efe79f942df98f4fa484083548a963bbc147922e"
account_public_key = "001d087916adfa92558e08a518f6f9422b075ce4d574e1f6e7969a09d120491e86"
protocol_public_key = "00baf27de71da3451b026174c5bae1894a4992e4071de56535d5730943f906337a"
dkg_public_key = "600000000c4e1986ea68ea4fc56f631af81fbfcd33fe8edb610d02c26d8c89b6dda54953f130598a35a019156372d67e6465a407181e49e5c4848cfe51562004d8641e348ae05c481cf841283e2870f10a3777ff0d91af27d5ae49243a44f97cb428aa92"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.129.150:26656"
tendermint_node_key = "009315aeaf8ac424645a88ae2eacdc0d1e8b2ff097022e3c7790804b43ce692e4b"
email = "aliefaisalanwar@gmail.com"
discord = "aliefaisala"
element = ""
telegram = "aliefaisala"
twitter = "fairstaking"
