[validator.Niloki]
consensus_public_key = "00ab54d711c0a25c69365dbf422592c61f80a12e956e24e64a5b67abc8e2bb43d2"
eth_cold_key = "010355df1d49837f2a431d75640b11165e28d75822070c94d05320a5171e004b5967"
eth_hot_key = "01035887d34f365704b114b68103f69be371eb9c35a1edc8c0049208114fe5747304"
account_public_key = "00541a13d3e24ca0ca51c172da7253c364b329e5fd6d54990afe31c08d9e73a4cd"
protocol_public_key = "003ea59f5d8d71bff60ea6616cab9a936b15b0e6a50c89da3db9131fe8973a9a97"
dkg_public_key = "60000000f7d9f5eb4c2a80acdbf2f424a78da915171090a71bd424db97a6f65abc1a75ab584461187fac0edd862f63d97d2e3802360af41bbd3c9ba37eb36b79c080066c932edcc2c61739f436e490f31104597762cbaadffd77c478409ac80a56134190"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.108.150:26656"
tendermint_node_key = "000e36c0bd3898702158b7ed6c28c9100154a0d506f5ac9d914404a98f21e609f9"
email = "niloki555@gmail.com"
discord = "niloki555"
telegram = "@niloki"
elements = "@niloki:matrix.org"
twitter = "@KrossLike"
