[validator.Vanlee]
consensus_public_key = "00062b0dece1902a0cc602e056770afb60596c4e80ea2bf30d36a194c47c7bc633"
eth_cold_key = "01029d47a3441aeecf1000c8f89a8eb149d70fcf077dd5045c13b08758922f6b43c3"
eth_hot_key = "01020d03b9786d9c767027bdfe06d4e796654f20095a91d94ef909c370715a17ac3c"
account_public_key = "009bf2731b4d6d018ed69a63a615037fc54c33096bf1dda7bc8abf7c8bb5129aae"
protocol_public_key = "00a882983398cf0b7285b071e347286392bafcf19df321d3f4a50ee54b6c41d16f"
dkg_public_key = "60000000b2835e2a8886b90a1854338496aeeffa3e76c7eff509309c94337f42ac9735c8f7ffc2a2d0c48231a20cd34020a7e21645641b90a0088247c97f74cfaa94b387ff4f908cd75d6953bc19997d7030cd4d55e0862f894918f3a06976834702bb8f"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "89.117.57.226:26656"
tendermint_node_key = "00ab95b81ef01099ab458de358439a9f8d437def6eee60019e752b611b96170a51"
email = "xiaofenix@gmail.com"
discord = "v_a_n_l_e_e"
elements = ""
telegram = "@SNVanlee"
twitter = "@Van_Lee83"