[validator.VinNodes]
consensus_public_key = "00372341a91d1d170012275a1859d32fd6d2390f08abb04759275b71d09d87678a"
eth_cold_key = "01039eec5b8632d200921924ee81dec08bd24a7c81d85a6610c641e95cc7cf4ffb8f"
eth_hot_key = "01028c48ba6e06551ed3ef3e2760397c8ca76bf31c2affe1281c662cd3cbe274aba7"
account_public_key = "008c35c136da8154e872d1bbc1933a9dd4936b3df139a94767d54eb40c934f9cf5"
protocol_public_key = "00b1ff1dbe03a8d89e04d0041a2620599c982f0e5f2b036ea8b64513ea8f1ead1d"
dkg_public_key = "60000000fe8d0aba9b40f72c96c352dc513837a7be405b493f42916b9d2faa4a22ff5b8beaa844d19f811e35527474249bb3651297bdbaf2306a1b51ccf9dcaaa0cb779aafe51bda59316ce1445d0bbf30f72c517ea6452930f66638bc02badb8fc27087"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "185.193.67.93:26656"
tendermint_node_key = "00d6b46cb7a98b368cd13bd49f5a5a4677ae4a38890b1ebaee516af5e00e09df4a"
email = "vinnodes@gmail.com"
discord = "wolfgangad"
elements = " "
telegram = "@wolfgangad"
twitter = "@vinnodes"
