[validator.wb3addctd]
consensus_public_key = "009d52027fda1b10c95fa8fad5deda09e89442223e553e985414be2ba1e6f296d3"
eth_cold_key = "01031db8b23b3abcc049bbb8e010b1a19ae8eb8af5e16ff7f4c0aaed270b6c38796a"
eth_hot_key = "01034644fd1b7a77255271bed116576f38ba91bb62089426888e6d72c72b049ce2f6"
account_public_key = "00d2fc688b14c31452b1c0081a02bbb9e669ac5b7c97a09f2790343decb3cf902b"
protocol_public_key = "00c64b10e107c595d8f62292cb4092853f876d3084539f4f69a70ea0efc314f5ed"
dkg_public_key = "60000000018c9c091232462e4bc0f51555a213610f55ed7eea7500b781499b3ccfe6168e1a920a101a403825165ab00f0d447f0b3b171dfd51bad6309dc4fbf055cd37596abc6f3c8f30d787727317a9236bbd0b8bb41e8819b57e7d0f75c183c6afd018"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.38.208:26656"
tendermint_node_key = "00dd206eda16727c5397f329e57b93dfe1db223ca360a387b35b7b7bfeb743bfe6"
elements = "web3addicted"
email = "virtualxgrape@gmail.com"
discord = "alekh_w"
telegram = "@alekh_w"
twitter = "@alekh_w"
