[validator.web3addicted]
consensus_public_key = "0045a46d05e0f6107e4638c73a3471c2eb3ced753b9eaf16466d4f74cd4d8f1bef"
eth_cold_key = "0102d5873f0b9176eebe7afbb3557195bcb9629fffa06fc8cd712de415f9029c2461"
eth_hot_key = "0103296e4cd72c32446e337201b7071ef1fab15c285f7b7617ed97adba14bcda8ef4"
account_public_key = "005fa6a417f6b6569830d394762e0c98d37ab960ecd59b72d2535aafb8d9bb59e2"
protocol_public_key = "005fff3ea06ba8652a6340bc13dfa7e6b6f11eed1301fe47751ae2f703c6fe0725"
dkg_public_key = "600000009e4c56f1607968b5114584bb01ca51723968d19eaef625312fb745d76ec9b6e421661c8c1c9ea864f132a19ca113cd128d3bc44e1e02a0e8735d234eea4fdb964e5a774ea6d3f4379632ca81122cc07bbdd5c947ae7e3808058ef6397a8af384"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.38.208:26656"
tendermint_node_key = "00ee47cc8e2dc781dcd3ec24cfb97a4d1f0e21ab37bc33b3dc0848acc96d5fadd7"
elements = "web3addicted"
email = "virtualxgrape@gmail.com"
discord = "alekh_w"
telegram = "@alekh_w"
twitter = "@alekh_w"
