[validator.web34ever]
consensus_public_key = "00d890a3b3975a19126547245d00fc0b8295ad4262ae9d7ead845cf27b9863fc6e"
eth_cold_key = "0102fb679bb15795953c012944a74277faa5a0786f57635f6ee5f3c4e46fbef56e59"
eth_hot_key = "01023ed0ae05f3fa294ea0bd3d611dadfb095639c8b68f8071af802b52b229e0055f"
account_public_key = "00cf07842acbd85353afe164bc458bf1dcb1cb2db20a7f6d7a84e2210254ffed52"
protocol_public_key = "00f9c5b99671778cc18a897dcfbb3cc1480cdef4dddfe86a59860f8ce75f6d4753"
dkg_public_key = "60000000ed04d5df22fd953809b92a88947d8765faae5a0f97aa057ec70e01c6d2e62f37e0052c708f29ca1b25b983c5e34cec03222f8965f45a3ef3c860b3ff2baf8697ddcfe49c3010bfd2a87bf42883ea6d18938f56192aca70fae37192ae9fad2603"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "69.197.6.24:26656"
tendermint_node_key = "00d12b02e4a4ebc842352ade3212885493b0041646d450ba5f065dfb971a4f8af9"
email = "web34ever@gmail.com"
discord = "web34ever"
elements = "@web3validator:matrix.org"
telegram = "web34ever"
twitter = "web34ever"
