[validator.zener]
consensus_public_key = "0020656f5db29e0a83cc2c19d9528a2a5670e0b1489ddb225f45c5a301d03363ed"
eth_cold_key = "0103aedbb9a81269ab8cca9eebd03ce45c921cb25493f7ee62f3d1ee3d2113d620b6"
eth_hot_key = "01025ecbfea8579860bef68f8ba9e0892377a4a126c1195aaa8cba4babe5c7dfca7e"
account_public_key = "00025f5f5887d4a772f906c9089ea3d98a584225d591e530caa2ba13a17128b720"
protocol_public_key = "00c51d77e21f59dbbf4cb1839d64c280c3f6fd968e8331e368965179272f6b54eb"
dkg_public_key = "600000001c932a40ca46b6cedad0da17f20a63351e0db4a266d1db0671af16cf0fd6eb4996d6e6b9b331cfc7636886dccd32110c1b41ddbfb75966fdc2d9ee12db0b363ab5c8697cf98afcec9b3ec10084ef008223074d1f3fa5842e59f2264b6dffa994"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = ":38.242.137.27"
tendermint_node_key = "00f3c47fbfeb4eb194aa45a5e8be99bc7b13c4dffe376989d2b4a28a6e566e7c7f"
email = "zenerbaba@gmail.com"
discord = "zener4115"
elements = ""
telegram = "@zenerbaba"
twitter = "@zenerbaba"
