[validator.ZeroKCap]
consensus_public_key = "0078a02f87497aa415889ec5b37cd440cd1b555bd9677dca2a513267a546b5e0a1"
eth_cold_key = "0102154a4f8af4b8a77e0fcb0a7a72a8cf1787fbe433f288ee54d8ab24e46b66c112"
eth_hot_key = "01020f11f9814e1976cb98302eedc6906b9823eb16fab3535a0fad331cfe838efcc1"
account_public_key = "009cc2d990d6e7cbcc01ba5f1726722ebde422330f4d281c975c323a8edbb84407"
protocol_public_key = "00e5ca0ac1974a4c966aeaf6604f6001dee4ce0e2f89dd931b923e042d172e0955"
dkg_public_key = "60000000fd2f0840c04d1bebbfa868b5d3b4c10255a135b8eb1115584f1633efbf0e6261ff68708d8100317eb9b0c5a58c776211b2c910ca751bf66cc5c4b141d177b86426c35ec1c541fde0c7f8b219b41a67d08ca4f6906b8e81923faca06601f2cd83"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "95.216.144.135:26656"
tendermint_node_key = "005613a566250985e879ae7b6c920ede3841bde8b4cf02bbf29b04541f1f6d22b7"
email = "larry@zerokcapital.com"
discord = "zklarry"
elements = "@larrylegend:matrix.org"
telegram = "@crypto_larry"
twitter = "@ZeroKCap"
