[validator.azstake]
consensus_public_key = "0004f25b4cd571df665dc89eaaaf12587537e9072c9884f19d1859591d003682c3"
eth_cold_key = "01024ada99f5ecc99935c8814b3cdde4fbc903474b2a44bac39fdb9395732672271f"
eth_hot_key = "01023c3a5de08720ca937f2f4cf0fbaba96b42b287048d48aa46f9a8f90bdb030a65"
account_public_key = "00863db28e5598f3a386de05a08ddce4a8e053ca3bb2b43ea8c88b208b4b44ad66"
protocol_public_key = "002fcf49434ca1bb97c07406241d103880898097a9639575fd34bf70666273f8f3"
dkg_public_key = "600000004ea3d97f75035fc54aeca8f99ac08b33862cb501070ef9c1fb89c488b0b022ba0ed2f21632d0add6342b10320f2e210b1f72e171c1045ae8a3b4cc52f4c7cd649c4b45812e9fd9d401d673d29b013c7e2717424f81353aad88b495cee7828385"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.84.115:41656"
tendermint_node_key = "004e7f3df4e40d309fc47c69376f600540185afbb688fce3658d99ee718f8cf90a"
