[validator.Clark]
consensus_public_key = "00a0e7aa62ba049f27cccb3c832c284851a8e4bec48b21e4dfa6eae1eb657d16c5"
eth_cold_key = "01025189d3e722e2ea6bfbe22a5272f0690892ecbf3b3929a8911ccce1b0fd64f5d7"
eth_hot_key = "0102f1928c240462cbb5c31f4aed0da3c280d16c23ec6dba3c6d2859e736a94241a8"
account_public_key = "00efc54da32fd8bf2b0456db3d2c86e7e41d978c9228f5cd06f16926b95a91e730"
protocol_public_key = "008941ee9abde9601070d33b8414143f1c75d21f144df5be1e17a19cc7acf523d6"
dkg_public_key = "60000000042c7528bc476ad6c3fdbb8f697c727a81a315f9ae091a5c94c7ae43e21c8419a8a92f15b8f479baaf63da91d826f317e14115bf18b388bec11c0fcb1e7629ae067d2b5f37229e16f6112d6eaf7077ca4d474153d2abcbc8fd2361b9371ca68f"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.30.90:26656"
tendermint_node_key = "00ae4cbffc3f69433e2ddbacb83b198c6c4b468810b6b50ef0fab55aee904a1dd7"
