[validator.cuongval]
consensus_public_key = "00d333ad4b6ca202765e3d304f442a23b5d3385ea4c14599357a95b98fb580efa7"
eth_cold_key = "0102500835e493077512bb60409bcadd4f21943c1935aee98865e204f64aaca200c6"
eth_hot_key = "0102648d7723c57dd9efa1ac9278681c86358530c1ea8af2037493ba2b2df788b140"
account_public_key = "0044d3efe82c5e648c6262d2a6980d6ca3d5c0fe8d3e9b5bde1ba7c0f7a401b38f"
protocol_public_key = "000e803e2008834cf06bcb48f0ff2aa1d0b06fac4388ee67f46b898bab637f71ef"
dkg_public_key = "60000000895f81d8791fac86a2640c9127c92623f4a25e908969aff548b58f676538058326a63918ccc4cd89573db5cbf24b9b163ca0da1a9ffa67772993f2c86363da4f5fe92d4bd03a2b0975e55afd52c8a369b436e56a23ac612d2129cd068aee0710"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "42.119.246.138:26656"
tendermint_node_key = "00030240b77d7186635bc22e474be59229a13fc4804a6b5c138d71a69dcacf365d"
