[validator.cyberalex]
consensus_public_key = "0098583ab406795b7d06745f7a475e8f714045078351d78319340443cd67fe0918"
eth_cold_key = "0102d7f06335ccb34e0c29fcb1ff0d0953c2de3a530ee7a23fa12f953f73f900d09c"
eth_hot_key = "01023130d9414e564e4d31422d4261f219a71f59906f03cf9c2cd9dc0109957250de"
account_public_key = "0011b593f6680b7ff2608ac83c5286eda8a7d88aaa4f47a5eb344a015eeeb53dc0"
protocol_public_key = "00fb2d19e1a8c9d71567491ae2f0c9be47268b4d5b2a21ecf6864250be65d415c2"
dkg_public_key = "60000000d84ba5cd21e71418e4603bc8cd3e7446ced2e5bf86796444b4785b1339a476946a4a75d1b3df0ffb9642e79ace6f720a685751acb2b79f75d80da2716dd5af87a36c58a0053dffdbdd462a697c217e7588f5bc974fe6e8ba0dbb878463d8c003"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "162.55.238.216:26656"
tendermint_node_key = "00968fb731272fa897a2271a52f427e70ec9d5d5eae8eba07109c1fbe25b75f3e6"
