[validator.Eiernaggen]
consensus_public_key = "00d7054d72d9e571bb3607e850269670c250e71318174cc6850930245b346f4894"
eth_cold_key = "010210fd382ccf6e1e609554ca33fed7531ffee5c88f78c2be4a0af9aafb59286b45"
eth_hot_key = "0103cd2a58167da7b74679605d4fbda91d60638f6d2991d19ba9c86e8de60e7947ce"
account_public_key = "002b115b84cc27bb5ffad16a8a5462d45c4b56d53803a996f22838cf34b8252d55"
protocol_public_key = "00199db205847091fa0ce894581a6079a8f2bd6c155a386a1cfda065c671378b53"
dkg_public_key = "60000000466eb9262476168bb06693372dccceee55606d3dcef8ee152ad82ec9110fc87dbe79c66bc5bdea71ae32496931257a153eaf511cfd3b8988e40b9a9710058cf391fbdbc3fc6d657ed269f7cfcec12fe6fd531cbd7bb4614249487073db708387"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "135.181.116.246:26656"
tendermint_node_key = "00582b6460f7e4adeb1afd57fed96205f7039edafeed6d4ed8ae46973c65f29aa8"
