[validator.HashBamboo]
consensus_public_key = "00f775d741d02c33aedd26096d9e6f8f4e2bf8a2895d3f0558bb5211f50ccb0243"
eth_cold_key = "01035c23d93be2ec4b969fe1185dbaa86512f7811b04baaec3e96fd4986554f7d735"
eth_hot_key = "0103da9fc4c01f2a082958bb6f41963c5916b7321ebdf0947e60ebff713bde96c64a"
account_public_key = "004ef0f5a6c7f2c6aee6d6c3aa7d84b5295bb0e4a50ab82c03b01e79ec2033864f"
protocol_public_key = "004746f8f2cd9a1e616d8e22f4efbd7baad4b3b0522c48514e0859f0f56ef15352"
dkg_public_key = "600000000041836d4af36c600b327cac90235186807ddd52c32695e5ed166ddbb1e397d62ee2993d037941378b0f483110d0911451fa3828940db3581c0ffd4d6028497bbb4dedb18661ae25b99ce26f618f8af15717a8ad6fd0a3a3e0fc543828d82c87"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "159.75.75.33:26656"
tendermint_node_key = "00c79edb0e168486e62787b66f8c6ddbc2e3596190d912df7bdf70315d9a70a270"