[validator.KingSuper]
consensus_public_key = "0060822b7ee257627e3da9e507e81931ea7faeb0001b5efb0e2917dc8a7cf4fda4"
eth_cold_key = "01020e8b740de119212a35a9b055f0da58ea9cf2c9f2d526fbf4c100e6026f17595c"
eth_hot_key = "0102f0e544d43474904cf7b4955807d0c3c8be5dd5a41cf5871a97d0c4674165ec1c"
account_public_key = "0006fd2598ba5c90fae59e77ee4195d4c14816215813bcc912d569d94448b34c33"
protocol_public_key = "00e28ec09dc1644926d348f5daca162747bfcec7d1b7342b03c89df8c3c53ae57e"
dkg_public_key = "600000007412adce8f2b964526be616054254050c48dff669884d36c4768eb802cd9fcc4cf5ff97c58722d5f66f1788fb196d1189e15790a6845832d14bc14d3bbe1be6ea22043f09db38adfd0ce3afc8007d3c4f436e7ba5793dd3a37b7f9123e0b0598"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.239.113:26656"
tendermint_node_key = "0010e054cdd78b7d15e5cc78789091a72d30b5773740221d1e67962f056b567113"
