[validator.Thoth]
consensus_public_key = "00f46b211abc2fa0953abd0e5370957fe579aefcd050bd6197a04bc34412e4133a"
eth_cold_key = "01029dc0e4aaea4ea3577a322d3a2f6e62a2a59a8594bbe070fdfc2fd7893d258ccd"
eth_hot_key = "01036773528a8108ddd0a2a4a77beef798e2e2519581504947fa69be5633de5c043f"
account_public_key = "00a7f0336056b41dc419a6207ac78f73da99ef537df0fcfbc0f89d2d579331c330"
protocol_public_key = "008d19073c160d706b95495f6f6f55d26e3f3771097515674a364eeea4cce8c038"
dkg_public_key = "600000007d72d934a0ab70402179c9b45889d05ff0bdf0959386fb507e04af84aed90f8226af105cabf1df0b43420d988b013c02228cf9e2ae656948062c1df86d0f800192444de8456c70d84a68713f2b0d63af557c21287ad005bdb630c3bcd50bc70c"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "135.181.232.121:22001"
tendermint_node_key = "0051a4c95bc7791eccd807e09c2eba8ba3c25cbcd9a490188a69e918641005d19a"
