[validator.UbikCapital]
consensus_public_key = "00c8c9b7f486d8e2f9e9fb38901c02423def3570b211f7a499c9120035bc85cfa9"
eth_cold_key = "0102c5dfb872f3a260c30623513ce0fc4acc64f14e25e6e63662256348b3bcc29e6e"
eth_hot_key = "010362880f7f706584f25a8768d860848c92f21e77d487b2a35b0f27e0fc4a1fb0e5"
account_public_key = "00382940a2504eaf4f22e6ebee16359778eabed3d8e6e83c0d17e46b30bedbe2c6"
protocol_public_key = "0033b9af8801d11d015709836f8e1fd7cf711084ebcdf3043e7e23ef25d9f90712"
dkg_public_key = "600000008c9b494ccef6cc20888a40783347642dc5040fd8a3b8ddfc1d250774a2c1060c4dbeb3f4489f607ccd3780a88431b30bd90d47747e21dc37ee16ac3c0b9c4e54ad04e66f92af1dd47f36a264dffb40a8d7077e56ad966ade6c72924aac1d8305"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "178.63.15.35:26656"
tendermint_node_key = "00ef83b742cdb833c6582f7f1a8737ffadb9c3c53b8308d7fb55342299c565960f"
