[validator.WellNode]
consensus_public_key = "008835e08aeb4ffd033cfd980484441009988cc5e1fe88e2a6defcffc854296964"
eth_cold_key = "010303e07c1a34e0596ab5364c82f924b1bb8de84261ab6805f9e7965c448240c9a6"
eth_hot_key = "0102a5a0ea314d43928fe930129333c10151150371cdaf7164769d1410cc77ce8664"
account_public_key = "00ec678b4a628ffd34d954f187f37a10ccd7b4c8b9a40430beb02db426cf50aaa6"
protocol_public_key = "00a5fb28449fdee52977c3451dcfad72c61c86924b8e3eecb69f1eabf51ede122a"
dkg_public_key = "60000000d6b065e7d696d21ae333227c84d682c4dcb249cd4c69b182efdb9e77cd043c2d8f549840386cec56062a1224cd3dfd065f80d3d94378e53a84e79587fc1c7dab45476b03f369d73c24a364817e69b237c74194de2c2afc10bf6bf9ad76eec483"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "84.46.249.217:26656"
tendermint_node_key = "0085cdb2ff7d3179ebde68c70a009a271c3785771b9205ea4d2faa5616fbdabe8e"
