[validator.888Tnso]
consensus_public_key = "001d5805b90d628ea8a1274281cab82c60a9fbb6161a02911176aa67677ac4bb56"
account_public_key = "00b850bb63a39f43646d36da373dfaf0b2119b746475d62418a66ec5b71752db54"
protocol_public_key = "00f1cdf4042cd5e24efb74df848c32d9f6612b814247e02fa0dc80b166838053c1"
dkg_public_key = "60000000be89a418a314a6b05967d57b8d56217e880cc08967b20afed2847083d05d9849fbac857e608d45b81b9494d9be230b182c9e4a3a6db2b0dbdbf775491535ffd213c14b315a3b69fa1b0c38f9ba8b0e4b50b6c1087cf3b25d626b463b356e5c8f"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "162.55.6.163:26656"
tendermint_node_key = "0001f1e5efc8d91090803e0f591666a496f33cb693446c65664aca7590fcea6977"
