[validator.blockonaut]
consensus_public_key = "004e6312720d6050cdc2f96d524d111b4c6436eda1bd4f770c80f56a45c9215aa3"
account_public_key = "00b737845842bcf084c2b7ed5152751b7d7e3ebf2336956c4b00493c7951d16e37"
protocol_public_key = "005f463e97532b8da706d53591b64711cb7724883d49b416ff40ec8504b622448b"
dkg_public_key = "6000000033377616692b885f1e1a0a45d5346a5749a7a51ea11b6228ef56100176c50316d4ccf50a817ab79aae2e0441fdf8b70da438e928c3f6824495a7575c5d55280fb>
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.201.15:28856"
tendermint_node_key = "008bbad57f38180f5cb198ec8c519b5547e28c913b0df95c72ddd90667ddd34454"
