[validator.Forbole]
consensus_public_key = "007fc989c5d87e6174950d60e882945dec25844216388fc07ebe105588e0b96e33"
account_public_key = "0056a71e536a38063a589781a40b64d5b5f3dbf5d928f24a604934f56465e9353b"
protocol_public_key = "0091405ce0d13696ec87b08d09b31896b07a971088720a534c5eb69949772506f7"
dkg_public_key = "60000000b6a177302437f5c658fde724623abad4c213663e58c641ade9fbaad2108da3629cf38ddca69425886bdafa6cea0ead0fbeb58a6f752634648eed5ef581de7a0206208ecc5a88d12d7a2acbe35f6c77e44ba86ba7ae69e37e471da3ad6502bf07"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "103.180.28.210:26656"
tendermint_node_key = "0024cc307811a8bcdd1b99e94a6d9df8830a0db1cd3177e99dae8af1826e709117"
