[validator.SBB]
consensus_public_key = "0014b77ff65cf7db27406323d8a33f50382a0ad8925342f857495a05cd12b83f21"
account_public_key = "0033a9ee67b20e199f49ea9ff1b600e688661be6b8eb9f3cc5e3c0788e45387733"
protocol_public_key = "00a21594585b211f83ff282bf0dd498c4c125f5593a9b99485f9a5608857668767"
dkg_public_key = "60000000fb041fd064036a29091020d2ae0448ae99b0fcaa855711de3888d22cb04c500ace6f8daa0fa53759e0c21f501c188201f3f8908e8366c339ae9406f55abc128a065cd58e4740e446446926beae56288ea1cdf4fea5a73a705fa4dd5a262c6a81"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "38.242.140.193:26656"
tendermint_node_key = "00ff567337a6ea370b3c6462857abc9ce643884fdbcb0c9bfade55ef9500713daf"
