[validator.BVS]
consensus_public_key = "0093af22c3ca5a0fc857a816f284924e5cb65e15c1847b48c9841aa85da9ff73c9"
account_public_key = "0032481101859d7bab0aa65df28a80b5c6869355aeb91b2a2b80154c286f44ca32"
protocol_public_key = "00788d4965b19853ef392315bc2f6871aa83261bb9e37d2584315e0db19e912630"
dkg_public_key = "60000000fb6cc6901df0220e63bbd41febaa3b9b5d9365a784f528ac6b3296ae6b0c455d588dc76976a4d49dd99e598c478d0e0776f1db846187f6b74649b2006835a66668df07d70bade9816cc444171bd8df5fbe9d0c38c2f6a95543f39def21935783"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "141.95.204.81:26656"
tendermint_node_key = "008b310381c386def3b00e31f88500a2583b79c812c3dccad2d60d89f4331e32d9"
