[validator.tRDM]
consensus_public_key = "0060fbf0f56c8dea5eff2464f12d891e962ea5e123937f0a6506f8f46c93c8815b"
account_public_key = "0047098514af2f613039d1f39e0f1b81660541a6288246f7f47355dc244391f70e"
protocol_public_key = "00bdcf0504419f83240fa6587c5fc1f5a1329e1b1286c0a94f0d26c83e0684e142"
dkg_public_key = "600000000f48d1feceb5147c822806bd16fc10114a01732b791afb2a92a52d7b3b70610a6527b49a1ecd0a5338440d753a488204b4a990bdb866e0be8f2db64758cecc4a965d2f85cdf0897497ead1e9cca3d25b9b4ab7dcc546afee93e04ec8a6021d8a"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "95.216.2.232:38656"
tendermint_node_key = "001ae294481f11d02b5b22dd5d79dd0470aea049589ec188520c8f6211295f8a14"